# Generated by Django 2.2.24 on 2024-07-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_auto_20240701_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipoCedula',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipoCliente',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipoRegimen',
            field=models.CharField(default='1', max_length=3),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipoVenta',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='convencional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observaciones',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
