# Generated by Django 2.2.24 on 2024-10-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_auto_20240716_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tiene_iva',
        ),
        migrations.AddField(
            model_name='opciones',
            name='correo',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opciones',
            name='direccion',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opciones',
            name='identificacion',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opciones',
            name='nombre_comercial',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opciones',
            name='obligado',
            field=models.CharField(choices=[('1', 'SI'), ('2', 'NO')], default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opciones',
            name='razon_social',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opciones',
            name='telefono',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opciones',
            name='tipo_regimen',
            field=models.CharField(choices=[('1', 'General'), ('2', 'RIMPE - EMPRENDEDORES'), ('3', 'RIMPE - NEGOCIOS POPULARES')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_actual',
            field=models.DecimalField(decimal_places=2, default='', max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='iva',
            field=models.CharField(choices=[('0', '0%'), ('1', '13%'), ('2', '12%'), ('3', '14%'), ('4', '15%'), ('5', '5%'), ('6', 'No Objeto'), ('7', 'Exento de IVA'), ('8', '8%')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_iva1',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=9),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_iva2',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoCedula',
            field=models.CharField(choices=[('1', 'Cédula'), ('2', 'Ruc'), ('3', 'Pasaporte')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoCliente',
            field=models.CharField(choices=[('1', 'Persona Natural'), ('2', 'Sociedad')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoRegimen',
            field=models.CharField(choices=[('1', 'General'), ('2', 'Rimpe - Emprendedores'), ('3', 'Rimpe - Negocios Populares')], max_length=3),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoVenta',
            field=models.CharField(choices=[('1', 'Local'), ('2', 'Exportación')], max_length=2),
        ),
        migrations.CreateModel(
            name='Secuencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('tipo_documento', models.CharField(max_length=2, verbose_name='Tipo de Documento')),
                ('secuencial', models.IntegerField(verbose_name='Número Secuencial')),
                ('establecimiento', models.CharField(max_length=3, verbose_name='Establecimiento')),
                ('punto_emision', models.CharField(max_length=3, verbose_name='Punto de Emisión')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('iva', models.BooleanField(default=True, verbose_name='IVA')),
                ('fiscal', models.BooleanField(default=True, verbose_name='Fiscal')),
                ('documento_electronico', models.BooleanField(default=True, verbose_name='Documento Electrónico')),
            ],
            options={
                'verbose_name': 'Secuencia',
                'verbose_name_plural': 'Secuencias',
                'db_table': 'inventario_secuencias',
                'unique_together': {('tipo_documento', 'establecimiento', 'punto_emision')},
            },
        ),
    ]
