# Generated by Django 2.2.24 on 2024-10-14 16:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_auto_20241014_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Opciones', to_field='valor_iva'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto_general',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='sub_monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
