# Generated by Django 2.2.24 on 2024-10-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_factura_base_imponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opciones',
            name='moneda',
        ),
        migrations.AlterField(
            model_name='opciones',
            name='correo',
            field=models.EmailField(default='correo@empresa.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='direccion',
            field=models.TextField(default='Calle Falsa 123', max_length=200),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='identificacion',
            field=models.CharField(default='1234567890', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='mensaje_factura',
            field=models.TextField(default='Gracias por su compra', null=True),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='nombre_comercial',
            field=models.CharField(default='Comercial X', max_length=200),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='nombre_negocio',
            field=models.CharField(default='Mi negocio', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='obligado',
            field=models.CharField(choices=[('1', 'SI'), ('2', 'NO')], default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='razon_social',
            field=models.CharField(default='Empresa Predeterminada', max_length=200),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='telefono',
            field=models.CharField(default='123456789', max_length=20),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='tipo_regimen',
            field=models.CharField(choices=[('1', 'General'), ('2', 'RIMPE - EMPRENDEDORES')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='valor_iva',
            field=models.IntegerField(default=12, unique=True),
        ),
    ]
