# Generated by Django 2.2.24 on 2024-10-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_auto_20241015_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='opciones',
            name='moneda',
            field=models.CharField(blank=True, default='USD', max_length=20, null=True),
        ),
    ]
