# Generated by Django 2.2.24 on 2024-10-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_auto_20241017_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuencia',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='secuencia',
            name='establecimiento',
            field=models.CharField(max_length=3, verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='secuencia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='secuencia',
            name='punto_emision',
            field=models.CharField(max_length=3, verbose_name='Punto de Emisión'),
        ),
        migrations.AlterField(
            model_name='secuencia',
            name='secuencial',
            field=models.IntegerField(verbose_name='Número Secuencial'),
        ),
        migrations.AlterField(
            model_name='secuencia',
            name='tipo_documento',
            field=models.CharField(max_length=2, verbose_name='Tipo de Documento'),
        ),
    ]
