# Generated by Django 2.2.24 on 2024-10-18 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_auto_20241017_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='fecha',
            new_name='fecha_emision',
        ),
        migrations.AddField(
            model_name='factura',
            name='codigo_producto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='concepto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='factura',
            name='identificacion_cliente',
            field=models.CharField(default='9999999999999', max_length=13),
        ),
        migrations.AddField(
            model_name='factura',
            name='nombre_cliente',
            field=models.CharField(default='CONSUMIDOR FINAL', max_length=100),
        ),
        migrations.AddField(
            model_name='factura',
            name='secuencia',
            field=models.CharField(default='000000000', max_length=9),
        ),
        migrations.AddField(
            model_name='factura',
            name='serie',
            field=models.CharField(default='001', max_length=3),
        ),
    ]
