# Generated by Django 2.2.24 on 2024-10-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_auto_20241018_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('descuento_permitido', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento Permitido')),
            ],
            options={
                'verbose_name': 'Facturador',
                'verbose_name_plural': 'Facturadores',
            },
        ),
    ]
