# Generated by Django 5.1.2 on 2024-10-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_facturador'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='clave_acceso',
            field=models.CharField(blank=True, max_length=49, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='secuencia',
            field=models.CharField(default='000000001', max_length=9),
        ),
        migrations.AlterField(
            model_name='factura',
            name='serie',
            field=models.CharField(default='001001', max_length=6),
        ),
    ]
