# Generated by Django 5.1.2 on 2024-10-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_factura_clave_acceso_alter_factura_secuencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallefactura',
            old_name='id_factura',
            new_name='factura',
        ),
        migrations.RenameField(
            model_name='detallefactura',
            old_name='id_producto',
            new_name='producto',
        ),
    ]
