# Generated by Django 5.1.2 on 2024-11-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_rename_id_factura_detallefactura_factura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
    ]
