# Generated by Django 5.1.2 on 2024-11-05 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.almacen'),
        ),
    ]
