# Generated by Django 5.1.2 on 2024-11-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0030_factura_almacen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='estado',
        ),
        migrations.AddField(
            model_name='almacen',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
