# Generated by Django 2.2.24 on 2024-11-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0033_auto_20241124_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='codigo_producto',
        ),
    ]
