# Generated by Django 2.2.24 on 2024-12-13 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0034_remove_factura_codigo_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='establecimiento',
            field=models.CharField(max_length=3, verbose_name='Código de establecimiento'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='identificacion_cliente',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='factura',
            name='nombre_cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='factura',
            name='punto_emision',
            field=models.CharField(max_length=3, verbose_name='Punto de emisión'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='secuencia',
            field=models.CharField(max_length=9, verbose_name='Número secuencial'),
        ),
        migrations.AlterField(
            model_name='secuencia',
            name='establecimiento',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)], verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='secuencia',
            name='punto_emision',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)], verbose_name='Punto de Emisión'),
        ),
        migrations.AlterField(
            model_name='secuencia',
            name='secuencial',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Número Secuencial'),
        ),
    ]
