# Generated by Django 2.2.24 on 2025-01-23 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0035_auto_20241213_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuencia',
            name='secuencial',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(9)], verbose_name='Número Secuencial'),
        ),
    ]
