# Generated by Django 2.2.24 on 2025-02-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0036_auto_20250123_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='iva',
        ),
    ]
