# Generated by Django 2.2.24 on 2025-05-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0037_remove_factura_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipoCedula',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipoIdentificacion',
            field=models.CharField(choices=[('04', 'RUC'), ('05', 'Cédula'), ('06', 'Pasaporte'), ('07', 'Consumidor Final'), ('08', 'Identificación del Exterior')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
