# Generated by Django 2.2.24 on 2025-06-06 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0038_auto_20250529_1103'),
    ]

    operations = [
        # Alter the column type in-place to avoid dropping the unique index used by FK
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        """
                        DO $$
                        BEGIN
                            IF EXISTS (
                                SELECT 1 FROM information_schema.columns
                                WHERE table_schema = 'public'
                                  AND table_name = 'inventario_cliente'
                                  AND column_name = 'cedula'
                            ) THEN
                                EXECUTE 'ALTER TABLE inventario_cliente ALTER COLUMN cedula TYPE varchar(13)';
                            END IF;
                        END
                        $$;
                        """
                    ),
                    reverse_sql=(
                        """
                        DO $$
                        BEGIN
                            IF EXISTS (
                                SELECT 1 FROM information_schema.columns
                                WHERE table_schema = 'public'
                                  AND table_name = 'inventario_cliente'
                                  AND column_name = 'cedula'
                            ) THEN
                                EXECUTE 'ALTER TABLE inventario_cliente ALTER COLUMN cedula TYPE varchar(12)';
                            END IF;
                        END
                        $$;
                        """
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='cliente',
                    name='cedula',
                    field=models.CharField(max_length=13, unique=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='secuencia',
            name='establecimiento',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='secuencia',
            name='punto_emision',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Punto de Emisión'),
        ),
        migrations.AlterField(
            model_name='secuencia',
            name='secuencial',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)], verbose_name='Número Secuencial'),
        ),
    ]
