# Generated by Django 2.2.24 on 2025-06-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0040_auto_20250613_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cedula',
            new_name='identificacion',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='cedula',
            new_name='identificacion_proveedor',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='apellido',
            new_name='nombre_comercial_proveedor',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre',
            new_name='razon_social_proveedor',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(default=1713959001, max_length=200),
            preserve_default=False,
        ),
    ]
