# Generated by Django 2.2.24 on 2025-06-16 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0041_auto_20250613_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturador',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facturador',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='facturador',
            table='inventario_facturador',
        ),
    ]
