# Generated by Django 2.2.24 on 2025-06-17 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0042_auto_20250616_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opciones',
            options={'verbose_name': 'Configuración de Empresa', 'verbose_name_plural': 'Configuración de Empresa'},
        ),
        migrations.AddField(
            model_name='opciones',
            name='es_agente_retencion',
            field=models.BooleanField(default=False, help_text='¿Su empresa es agente de retención?'),
        ),
        migrations.AddField(
            model_name='opciones',
            name='es_contribuyente_especial',
            field=models.BooleanField(default=False, help_text='¿Su empresa es contribuyente especial?'),
        ),
        migrations.AddField(
            model_name='opciones',
            name='numero_agente_retencion',
            field=models.CharField(blank=True, help_text='Número de resolución de agente de retención', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='opciones',
            name='numero_contribuyente_especial',
            field=models.CharField(blank=True, help_text='Número de resolución de contribuyente especial', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='correo',
            field=models.EmailField(default='configurar@empresa.com', help_text='Email principal de su empresa', max_length=100),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='direccion',
            field=models.TextField(default='[CONFIGURAR DIRECCIÓN]', help_text='Dirección principal matriz de su empresa', max_length=300),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='identificacion',
            field=models.CharField(default='0000000000000', help_text='RUC de 13 dígitos de su empresa', max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'El RUC debe tener exactamente 13 dígitos')]),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='mensaje_factura',
            field=models.TextField(blank=True, default='Gracias por su compra', help_text='Mensaje que aparece en las facturas', null=True),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='moneda',
            field=models.CharField(default='DOLAR', help_text='Moneda oficial (DOLAR para Ecuador)', max_length=20),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='nombre_comercial',
            field=models.CharField(default='[CONFIGURAR NOMBRE COMERCIAL]', help_text='Nombre comercial de su empresa (opcional)', max_length=300),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='nombre_negocio',
            field=models.CharField(blank=True, default='Mi Negocio', help_text='Nombre corto para mostrar en reportes', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='obligado',
            field=models.CharField(choices=[('SI', 'SÍ'), ('NO', 'NO')], default='SI', help_text='¿Está obligado a llevar contabilidad?', max_length=2),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='razon_social',
            field=models.CharField(default='[CONFIGURAR RAZÓN SOCIAL]', help_text='Razón social según consta en el RUC', max_length=300),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='telefono',
            field=models.CharField(default='0000000000', help_text='Teléfono principal de contacto', max_length=20),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='tipo_regimen',
            field=models.CharField(choices=[('GENERAL', 'Régimen General'), ('RIMPE', 'RIMPE - Emprendedores')], default='GENERAL', help_text='Tipo de régimen tributario', max_length=20),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='valor_iva',
            field=models.IntegerField(default=12, help_text='Porcentaje de IVA vigente en Ecuador', unique=True),
        ),
    ]
