# Generated by Django 2.2.24 on 2025-06-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0043_auto_20250616_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opciones',
            options={},
        ),
        migrations.AddField(
            model_name='opciones',
            name='tipo_ambiente',
            field=models.CharField(default='1', help_text='Ambiente: 1=Pruebas, 2=Producción (Solo técnicos)', max_length=1),
        ),
        migrations.AddField(
            model_name='opciones',
            name='tipo_emision',
            field=models.CharField(default='1', help_text='Tipo emisión: 1=Normal (único permitido en método offline)', max_length=1),
        ),
        migrations.AlterField(
            model_name='opciones',
            name='valor_iva',
            field=models.IntegerField(default=15, help_text='Porcentaje de IVA vigente en Ecuador', unique=True),
        ),
    ]
