# Generated by Django 2.2.24 on 2025-06-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0044_auto_20250617_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['descripcion'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='opciones',
            old_name='direccion',
            new_name='direccion_establecimiento',
        ),
        migrations.AlterField(
            model_name='producto',
            name='iva',
            field=models.CharField(choices=[('0', '0%'), ('5', '5%'), ('2', '12%'), ('10', '13%'), ('3', '14%'), ('4', '15%'), ('6', 'No Objeto'), ('7', 'Exento de IVA'), ('8', 'IVA Diferenciado')], max_length=10),
        ),
    ]
