# Generated by Django 2.2.24 on 2025-06-27 15:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0045_auto_20250625_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento aplicado a este ítem específico (OBLIGATORIO en XSD)', max_digits=14),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento aplicado (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='precio_sin_subsidio',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Precio sin subsidio para este ítem (opcional)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='facturador',
            field=models.ForeignKey(default=1, help_text='Facturador que emite la factura', on_delete=django.db.models.deletion.PROTECT, to='inventario.Facturador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='guia_remision',
            field=models.CharField(blank=True, help_text='Guía de remisión (opcional)', max_length=17, null=True, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}-\\d{9}$', 'Formato: 001-001-000000001')]),
        ),
        migrations.AddField(
            model_name='factura',
            name='placa',
            field=models.CharField(blank=True, help_text='Placa del vehículo (opcional, obligatorio para combustibles)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='propina',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Propina (opcional según XSD)', max_digits=14),
        ),
        migrations.AddField(
            model_name='factura',
            name='total_descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total de descuentos aplicados (OBLIGATORIO en XSD)', max_digits=14),
        ),
        migrations.AddField(
            model_name='factura',
            name='total_subsidio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total de subsidios aplicados (opcional)', max_digits=14),
        ),
        migrations.AddField(
            model_name='factura',
            name='valor_retencion_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor de retención de IVA (opcional)', max_digits=14),
        ),
        migrations.AddField(
            model_name='factura',
            name='valor_retencion_renta',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor de retención en la fuente (opcional)', max_digits=14),
        ),
        migrations.CreateModel(
            name='TipoNegociable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(help_text='Email del receptor para notificación masiva de facturas negociables', max_length=100, verbose_name='Correo del Receptor')),
                ('estado_negociacion', models.CharField(choices=[('pendiente', 'Pendiente de Negociación'), ('en_proceso', 'En Proceso de Negociación'), ('negociada', 'Negociada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], default='pendiente', max_length=20, verbose_name='Estado de Negociación')),
                ('fecha_notificacion', models.DateTimeField(blank=True, help_text='Fecha en que se notificó al receptor', null=True, verbose_name='Fecha de Notificación')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, help_text='Fecha en que el receptor aceptó la factura', null=True, verbose_name='Fecha de Aceptación')),
                ('fecha_vencimiento_negociacion', models.DateField(blank=True, help_text='Fecha límite para negociar la factura', null=True, verbose_name='Fecha Vencimiento Negociación')),
                ('entidad_negociadora', models.CharField(blank=True, help_text='Nombre de la entidad que negocia la factura', max_length=200, null=True, verbose_name='Entidad Negociadora')),
                ('valor_negociado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor por el cual se negoció la factura', max_digits=14, null=True, verbose_name='Valor Negociado')),
                ('tasa_descuento', models.DecimalField(blank=True, decimal_places=4, help_text='Tasa de descuento aplicada en la negociación (0.0000 - 1.0000)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Tasa de Descuento')),
                ('observaciones_negociacion', models.TextField(blank=True, help_text='Notas sobre el proceso de negociación', null=True, verbose_name='Observaciones de Negociación')),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_negociable', to='inventario.Factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Tipo Negociable',
                'verbose_name_plural': 'Tipos Negociables',
            },
        ),
        migrations.CreateModel(
            name='MaquinaFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Marca de la máquina fiscal (ej: EPSON, BIXOLON, etc.)', max_length=30, verbose_name='Marca')),
                ('modelo', models.CharField(help_text='Modelo específico de la máquina fiscal', max_length=30, verbose_name='Modelo')),
                ('serie', models.CharField(help_text='Número de serie único de la máquina fiscal', max_length=30, verbose_name='Número de Serie')),
                ('fecha_instalacion', models.DateField(blank=True, help_text='Fecha en que se instaló la máquina fiscal', null=True, verbose_name='Fecha de Instalación')),
                ('activa', models.BooleanField(default=True, help_text='¿La máquina fiscal está activa?', verbose_name='Activa')),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación física de la máquina (ej: Caja 1, Mostrador, etc.)', max_length=100, null=True, verbose_name='Ubicación')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la máquina fiscal', null=True, verbose_name='Observaciones')),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maquina_fiscal', to='inventario.Factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Máquina Fiscal',
                'verbose_name_plural': 'Máquinas Fiscales',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(choices=[('01', 'Sin utilización del sistema financiero'), ('15', 'Compensación de deudas'), ('16', 'Tarjeta de débito'), ('17', 'Dinero electrónico'), ('18', 'Tarjeta prepago'), ('19', 'Tarjeta de crédito'), ('20', 'Otros con utilización del sistema financiero'), ('21', 'Endoso de títulos'), ('02', 'Cheque propio'), ('03', 'Cheque certificado'), ('04', 'Cheque de gerencia'), ('05', 'Cheque del exterior'), ('06', 'Débito de cuenta'), ('07', 'Transferencia propio banco'), ('08', 'Transferencia otro banco nacional'), ('09', 'Transferencia banco exterior'), ('10', 'Tarjeta de crédito nacional'), ('11', 'Tarjeta de crédito internacional'), ('12', 'Giro'), ('13', 'Depósito en cuenta (corriente/ahorros)'), ('14', 'Endoso de inversión')], default='01', max_length=2, verbose_name='Forma de Pago')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Total')),
                ('plazo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Plazo')),
                ('unidad_tiempo', models.CharField(blank=True, choices=[('dias', 'Días'), ('semanas', 'Semanas'), ('meses', 'Meses'), ('años', 'Años')], max_length=10, null=True, verbose_name='Unidad de Tiempo')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pago', to='inventario.Factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
            },
        ),
        migrations.CreateModel(
            name='CampoAdicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: E-MAIL, TELÉFONO, OBSERVACIONES, etc.', max_length=300, verbose_name='Nombre del Campo')),
                ('valor', models.CharField(help_text='Contenido del campo adicional', max_length=300, verbose_name='Valor del Campo')),
                ('orden', models.PositiveSmallIntegerField(default=1, help_text='Orden de aparición en la factura (1-15)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Orden')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_adicionales', to='inventario.Factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Campo Adicional',
                'verbose_name_plural': 'Campos Adicionales',
                'ordering': ['factura', 'orden', 'nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='maquinafiscal',
            constraint=models.UniqueConstraint(fields=('serie',), name='unique_serie_maquina_fiscal'),
        ),
        migrations.AlterUniqueTogether(
            name='formapago',
            unique_together={('factura', 'forma_pago')},
        ),
        migrations.AlterUniqueTogether(
            name='campoadicional',
            unique_together={('factura', 'nombre')},
        ),
    ]
