# Generated by Django 2.2.24 on 2025-06-27 16:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0046_auto_20250627_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpuestoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('2', 'IVA'), ('3', 'ICE'), ('5', 'IRBPNR')], default='2', help_text='Código según tabla 16 SRI: 2=IVA, 3=ICE, 5=IRBPNR', max_length=1, verbose_name='Código de Impuesto')),
                ('codigo_porcentaje', models.CharField(choices=[('0', '0%'), ('2', '12%'), ('3', '14%'), ('4', '15%'), ('5', '5%'), ('6', 'No Objeto'), ('7', 'Exento'), ('8', '8%'), ('10', '13%')], help_text='Código según tabla 17 SRI', max_length=4, verbose_name='Código Porcentaje')),
                ('tarifa', models.DecimalField(decimal_places=2, help_text='Porcentaje del impuesto', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tarifa (%)')),
                ('base_imponible', models.DecimalField(decimal_places=2, help_text='Subtotal del ítem gravado con este impuesto', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Base Imponible')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor del impuesto para este ítem', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor del Impuesto')),
                ('detalle_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='inventario.DetalleFactura', verbose_name='Detalle de Factura')),
            ],
            options={
                'verbose_name': 'Impuesto de Detalle',
                'verbose_name_plural': 'Impuestos de Detalles',
                'ordering': ['detalle_factura', 'codigo', 'codigo_porcentaje'],
                'unique_together': {('detalle_factura', 'codigo', 'codigo_porcentaje')},
            },
        ),
        migrations.CreateModel(
            name='TotalImpuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('2', 'IVA'), ('3', 'ICE'), ('5', 'IRBPNR')], default='2', help_text='Código según tabla 16 SRI: 2=IVA, 3=ICE, 5=IRBPNR', max_length=1, verbose_name='Código de Impuesto')),
                ('codigo_porcentaje', models.CharField(choices=[('0', '0%'), ('2', '12%'), ('3', '14%'), ('4', '15%'), ('5', '5%'), ('6', 'No Objeto'), ('7', 'Exento'), ('8', '8%'), ('10', '13%')], help_text='Código según tabla 17 SRI', max_length=4, verbose_name='Código Porcentaje')),
                ('descuento_adicional', models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento adicional aplicado (opcional)', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento Adicional')),
                ('base_imponible', models.DecimalField(decimal_places=2, help_text='Subtotal gravado con este impuesto', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Base Imponible')),
                ('tarifa', models.DecimalField(blank=True, decimal_places=4, help_text='Porcentaje del impuesto (se calcula automáticamente)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tarifa (%)')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor total del impuesto', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor del Impuesto')),
                ('valor_devolucion_iva', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor para devolución automática del IVA (opcional)', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Devolución IVA')),
            ],
            options={
                'verbose_name': 'Total de Impuesto',
                'verbose_name_plural': 'Totales de Impuestos',
                'ordering': ['factura', 'codigo', 'codigo_porcentaje'],
            },
        ),
        migrations.RemoveField(
            model_name='tiponegociable',
            name='factura',
        ),
        migrations.AlterModelOptions(
            name='opciones',
            options={'verbose_name': 'Configuración de Empresa', 'verbose_name_plural': 'Configuración de Empresa'},
        ),
        migrations.AlterField(
            model_name='factura',
            name='facturador',
            field=models.ForeignKey(blank=True, help_text='Facturador que emite la factura', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='inventario.Facturador', verbose_name='Facturador'),
        ),
        migrations.DeleteModel(
            name='MaquinaFiscal',
        ),
        migrations.DeleteModel(
            name='TipoNegociable',
        ),
        migrations.AddField(
            model_name='totalimpuesto',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totales_impuestos', to='inventario.Factura', verbose_name='Factura'),
        ),
        migrations.AlterUniqueTogether(
            name='totalimpuesto',
            unique_together={('factura', 'codigo', 'codigo_porcentaje')},
        ),
    ]
