# Generated by Django 2.2.24 on 2025-06-27 16:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0047_auto_20250627_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Marca de la máquina fiscal (ej: EPSON, BIXOLON, etc.)', max_length=30, verbose_name='Marca')),
                ('modelo', models.CharField(help_text='Modelo específico de la máquina fiscal', max_length=30, verbose_name='Modelo')),
                ('serie', models.CharField(help_text='Número de serie único de la máquina fiscal', max_length=30, verbose_name='Número de Serie')),
                ('fecha_instalacion', models.DateField(blank=True, help_text='Fecha en que se instaló la máquina fiscal', null=True, verbose_name='Fecha de Instalación')),
                ('activa', models.BooleanField(default=True, help_text='¿La máquina fiscal está activa?', verbose_name='Activa')),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación física de la máquina (ej: Caja 1, Mostrador, etc.)', max_length=100, null=True, verbose_name='Ubicación')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la máquina fiscal', null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Máquina Fiscal',
                'verbose_name_plural': 'Máquinas Fiscales',
            },
        ),
        migrations.CreateModel(
            name='TipoNegociable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(help_text='Email del receptor para notificación masiva de facturas negociables', max_length=100, verbose_name='Correo del Receptor')),
                ('estado_negociacion', models.CharField(choices=[('pendiente', 'Pendiente de Negociación'), ('en_proceso', 'En Proceso de Negociación'), ('negociada', 'Negociada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], default='pendiente', max_length=20, verbose_name='Estado de Negociación')),
                ('fecha_notificacion', models.DateTimeField(blank=True, help_text='Fecha en que se notificó al receptor', null=True, verbose_name='Fecha de Notificación')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, help_text='Fecha en que el receptor aceptó la factura', null=True, verbose_name='Fecha de Aceptación')),
                ('fecha_vencimiento_negociacion', models.DateField(blank=True, help_text='Fecha límite para negociar la factura', null=True, verbose_name='Fecha Vencimiento Negociación')),
                ('entidad_negociadora', models.CharField(blank=True, help_text='Nombre de la entidad que negocia la factura', max_length=200, null=True, verbose_name='Entidad Negociadora')),
                ('valor_negociado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor por el cual se negoció la factura', max_digits=14, null=True, verbose_name='Valor Negociado')),
                ('tasa_descuento', models.DecimalField(blank=True, decimal_places=4, help_text='Tasa de descuento aplicada en la negociación (0.0000 - 1.0000)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Tasa de Descuento')),
                ('observaciones_negociacion', models.TextField(blank=True, help_text='Notas sobre el proceso de negociación', null=True, verbose_name='Observaciones de Negociación')),
            ],
            options={
                'verbose_name': 'Tipo Negociable',
                'verbose_name_plural': 'Tipos Negociables',
            },
        ),
        migrations.AlterUniqueTogether(
            name='totalimpuesto',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='totalimpuesto',
            name='factura',
        ),
        migrations.AlterModelOptions(
            name='opciones',
            options={},
        ),
        migrations.AlterField(
            model_name='factura',
            name='facturador',
            field=models.ForeignKey(default=1, help_text='Facturador que emite la factura', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='inventario.Facturador', verbose_name='Facturador'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ImpuestoDetalle',
        ),
        migrations.DeleteModel(
            name='TotalImpuesto',
        ),
        migrations.AddField(
            model_name='tiponegociable',
            name='factura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_negociable', to='inventario.Factura', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='maquinafiscal',
            name='factura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maquina_fiscal', to='inventario.Factura', verbose_name='Factura'),
        ),
        migrations.AddConstraint(
            model_name='maquinafiscal',
            constraint=models.UniqueConstraint(fields=('serie',), name='unique_serie_maquina_fiscal'),
        ),
    ]
