# Generated by Django 2.2.24 on 2025-06-27 17:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0048_auto_20250627_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpuestoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('2', 'IVA'), ('3', 'ICE'), ('5', 'IRBPNR')], max_length=1)),
                ('codigo_porcentaje', models.CharField(max_length=4)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('detalle_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos_detalle', to='inventario.DetalleFactura')),
            ],
        ),
        migrations.CreateModel(
            name='TotalImpuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('2', 'IVA'), ('3', 'ICE'), ('5', 'IRBPNR'), ('6', 'ISD')], help_text='Código del impuesto según tabla 16 SRI', max_length=1)),
                ('codigo_porcentaje', models.CharField(help_text='Código específico del porcentaje (ej: 2, 0, 6, 7)', max_length=4)),
                ('base_imponible', models.DecimalField(decimal_places=2, help_text='Base sobre la cual se calcula el impuesto', max_digits=14)),
                ('tarifa', models.DecimalField(decimal_places=2, help_text='Porcentaje del impuesto (ej: 15.00 para 15%)', max_digits=4)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor del impuesto = base_imponible * (tarifa/100)', max_digits=14)),
                ('descuento_adicional', models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento adicional aplicable solo a IVA', max_digits=14)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totales_impuestos', to='inventario.Factura')),
            ],
            options={
                'verbose_name': 'Total Impuesto',
                'verbose_name_plural': 'Totales Impuestos',
                'unique_together': {('factura', 'codigo', 'codigo_porcentaje')},
            },
        ),
        migrations.CreateModel(
            name='DetalleAdicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del detalle adicional (ej: Marca, Modelo, Serie)', max_length=300)),
                ('valor', models.CharField(help_text='Valor del detalle adicional', max_length=300)),
                ('orden', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('detalle_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_adicionales', to='inventario.DetalleFactura')),
            ],
            options={
                'verbose_name': 'Detalle Adicional',
                'verbose_name_plural': 'Detalles Adicionales',
                'ordering': ['detalle_factura', 'orden'],
                'unique_together': {('detalle_factura', 'nombre')},
            },
        ),
    ]
