# Generated by Django 2.2.24 on 2025-07-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0049_detalleadicional_impuestodetalle_totalimpuesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opciones',
            options={'verbose_name': 'Configuración de Empresa', 'verbose_name_plural': 'Configuración de Empresa'},
        ),
        migrations.AlterField(
            model_name='formapago',
            name='forma_pago',
            field=models.CharField(choices=[('01', 'Sin utilización del sistema financiero'), ('15', 'Compensación de deudas'), ('16', 'Tarjeta de débito'), ('17', 'Dinero electrónico'), ('18', 'Tarjeta prepago'), ('19', 'Tarjeta de crédito'), ('20', 'Otros con utilización del sistema financiero'), ('21', 'Endoso de títulos')], default='01', max_length=2, verbose_name='Forma de Pago'),
        ),
    ]
