# Generated by Django 2.2.24 on 2025-07-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0050_auto_20250702_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapago',
            name='caja',
            field=models.CharField(choices=[('caja_ventas', 'Caja Ventas'), ('caja_principal', 'Caja Principal'), ('efectivo', 'Efectivo'), ('banco', 'Banco')], default='caja_ventas', max_length=50, verbose_name='Caja'),
        ),
    ]
