# Generated by Django 2.2.24 on 2025-07-11 22:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0051_formapago_caja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(help_text='Nombre del banco (ej: Banco Pichincha, Banco de Guayaquil)', max_length=100, verbose_name='Banco')),
                ('titular', models.CharField(help_text='Nombre completo del titular de la cuenta', max_length=200, verbose_name='Titular')),
                ('numero_cuenta', models.CharField(help_text='Número de la cuenta bancaria', max_length=50, unique=True, verbose_name='Número de Cuenta')),
                ('activo', models.BooleanField(default=True, help_text='¿La cuenta bancaria está activa?', verbose_name='Activo')),
                ('tipo_cuenta', models.CharField(choices=[('CORRIENTE', 'Corriente'), ('AHORROS', 'Ahorros'), ('VISTA', 'Vista'), ('PLAZO_FIJO', 'Plazo Fijo')], default='CORRIENTE', max_length=20, verbose_name='Tipo de Cuenta')),
                ('fecha_apertura', models.DateField(help_text='Fecha en que se abrió la cuenta', verbose_name='Fecha Apertura')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto del banco o sucursal', max_length=20, null=True, verbose_name='Teléfono')),
                ('secuencial_cheque', models.IntegerField(default=1, help_text='Próximo número de cheque a utilizar', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Secuencial Cheque')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo inicial de la cuenta (opcional)', max_digits=14, verbose_name='Saldo Inicial')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la cuenta bancaria', null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó esta cuenta bancaria', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['banco', 'titular'],
                'unique_together': {('banco', 'numero_cuenta')},
            },
        ),
    ]
