# Generated by Django 2.2.24 on 2025-07-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0053_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='saldo_inicial',
        ),
    ]
