# Generated by Django 2.2.24 on 2025-07-16 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0054_remove_banco_saldo_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapago',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formas_pago', to='inventario.Caja', verbose_name='Caja'),
        ),
    ]
