# Generated by Django 2.2.24 on 2025-07-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0055_auto_20250716_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='opciones',
            name='firma_electronica',
            field=models.FileField(blank=True, help_text='Archivo de firma electrónica (.p12 o .pfx). Se almacena cifrado y nunca se expone públicamente.', null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='opciones',
            name='password_firma',
            field=models.CharField(blank=True, help_text='Contraseña de la firma electrónica (se recomienda cifrar este campo y nunca mostrarlo en texto plano).', max_length=128, null=True),
        ),
    ]
