# Generated by Django 2.2.24 on 2025-07-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0056_auto_20250717_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opciones',
            name='tipo_ambiente',
            field=models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', help_text='Ambiente: 1=Pruebas, 2=Producción (Solo técnicos)', max_length=1),
        ),
    ]
