# Generated by Django 2.2.24 on 2025-07-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0057_auto_20250717_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='opciones',
            name='fecha_caducidad_firma',
            field=models.DateField(blank=True, help_text='Fecha de caducidad del certificado de firma electrónica', null=True),
        ),
    ]
