# Generated by Django 2.2.24 on 2025-07-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0059_auto_20250718_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opciones',
            name='numero_agente_retencion',
            field=models.CharField(blank=True, choices=[('NAC-GTRRIOC21-00000001', 'NAC-GTRRIOC21-00000001'), ('NAC-GTRRIOC22-00000001', 'NAC-GTRRIOC22-00000001'), ('NAC-GTRRIOC22-00000003', 'NAC-GTRRIOC22-00000003'), ('NAC-DGERCGC24-00000014', 'NAC-DGERCGC24-00000014'), ('NAC-DGERCGC25-00000010', 'NAC-DGERCGC25-00000010')], help_text='Número de resolución de agente de retención', max_length=30, null=True),
        ),
    ]
