# Generated by Django 2.2.24 on 2025-07-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0061_auto_20250718_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opciones',
            options={},
        ),
    ]
