# Generated by Django 2.2.24 on 2025-07-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0062_auto_20250721_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='opciones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
