# Generated by Django 2.2.24 on 2025-07-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0063_opciones_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('iva', models.CharField(choices=[('0', '0%'), ('5', '5%'), ('2', '12%'), ('10', '13%'), ('3', '14%'), ('4', '15%'), ('6', 'No Objeto'), ('7', 'Exento de IVA'), ('8', 'IVA Diferenciado')], default='2', max_length=10)),
                ('precio1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
