# Generated by Django 2.2.24 on 2025-07-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0064_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Servicio'),
        ),
    ]
