# Generated by Django 2.2.24 on 2025-07-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0065_detallefactura_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
