# Generated by Django 2.2.24 on 2025-07-29 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0066_auto_20250728_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleadicional',
            options={'ordering': ['detalle_factura', 'orden', 'nombre'], 'verbose_name': 'Detalle Adicional', 'verbose_name_plural': 'Detalles Adicionales'},
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto'),
        ),
    ]
