# Generated by Django 5.1.3 on 2025-08-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0068_alter_almacen_id_alter_banco_id_alter_caja_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='nombre',
        ),
    ]
