# Generated by Django 5.1.3 on 2025-08-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0069_remove_servicio_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo inicial de la cuenta', max_digits=15, verbose_name='Saldo Inicial'),
        ),
    ]
