# Generated by Django 5.1.3 on 2025-08-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0070_banco_saldo_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado_sri',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDA', 'Recibida por SRI'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada'), ('ERROR', 'Error en procesamiento')], default='PENDIENTE', help_text='Estado de la factura en el SRI', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de autorización del SRI', null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='mensaje_sri',
            field=models.TextField(blank=True, help_text='Mensaje principal del SRI', null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='mensaje_sri_detalle',
            field=models.TextField(blank=True, help_text='Detalle completo de mensajes del SRI', null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_autorizacion',
            field=models.CharField(blank=True, help_text='Número de autorización del SRI', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='ride_autorizado',
            field=models.FileField(blank=True, help_text='RIDE (PDF) autorizado', null=True, upload_to='rides/'),
        ),
        migrations.AddField(
            model_name='factura',
            name='xml_autorizado',
            field=models.TextField(blank=True, help_text='XML autorizado devuelto por el SRI', null=True),
        ),
    ]
