# Generated by Django para actualizar modelo Proveedor

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0072_factura_estado'),
    ]

    operations = [
        # Agregar campo tipoIdentificacion
        migrations.AddField(
            model_name='proveedor',
            name='tipoIdentificacion',
            field=models.CharField(
                max_length=2,
                choices=[
                    ('04', 'RUC'),
                    ('05', 'Cédula'),
                    ('06', 'Pasaporte'),
                    ('07', 'Consumidor Final'),
                    ('08', 'Identificación del Exterior'),
                ],
                default='05'  # Por defecto será Cédula
            ),
        ),
        
        # Ampliar campo identificacion_proveedor de 12 a 13 caracteres
        migrations.AlterField(
            model_name='proveedor',
            name='identificacion_proveedor',
            field=models.CharField(max_length=13, unique=True),
        ),
        
        # Ampliar campo razon_social_proveedor de 40 a 200 caracteres
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social_proveedor',
            field=models.CharField(max_length=200),
        ),
        
        # Ampliar y hacer opcional campo nombre_comercial_proveedor
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_comercial_proveedor',
            field=models.CharField(max_length=200, blank=True, null=True),
        ),
        
        # Hacer opcional campo telefono
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
        
        # Hacer opcional campo nacimiento
        migrations.AlterField(
            model_name='proveedor',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        
        # Agregar campo observaciones
        migrations.AddField(
            model_name='proveedor',
            name='observaciones',
            field=models.CharField(max_length=300, blank=True, null=True),
        ),
        
        # Agregar campo convencional
        migrations.AddField(
            model_name='proveedor',
            name='convencional',
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
        
        # Agregar campo tipoVenta
        migrations.AddField(
            model_name='proveedor',
            name='tipoVenta',
            field=models.CharField(
                max_length=2,
                choices=[
                    ('1', 'Local'),
                    ('2', 'Exportación'),
                ],
                default='1'
            ),
        ),
        
        # Agregar campo tipoRegimen
        migrations.AddField(
            model_name='proveedor',
            name='tipoRegimen',
            field=models.CharField(
                max_length=3,
                choices=[
                    ('1', 'General'),
                    ('2', 'Rimpe - Emprendedores'),
                    ('3', 'Rimpe - Negocios Populares'),
                ],
                default='1'
            ),
        ),
        
        # Agregar campo tipoProveedor
        migrations.AddField(
            model_name='proveedor',
            name='tipoProveedor',
            field=models.CharField(
                max_length=2,
                choices=[
                    ('1', 'Persona Natural'),
                    ('2', 'Sociedad'),
                ],
                default='1'
            ),
        ),
    ]
