# Generated by Django 5.2.5 on 2025-08-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0073_actualizar_proveedor_campos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado_sri',
            field=models.CharField(blank=True, choices=[('', 'Local - No enviado al SRI'), ('PENDIENTE', 'Pendiente'), ('RECIBIDA', 'Recibida por SRI'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada'), ('ERROR', 'Error en procesamiento')], default='', help_text='Estado de la factura en el SRI', max_length=20),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='forma_pago',
            field=models.CharField(choices=[('01', 'Sin utilización del sistema financiero'), ('15', 'Compensación de deudas'), ('16', 'Tarjeta de débito'), ('17', 'Dinero electrónico'), ('18', 'Tarjeta prepago'), ('19', 'Tarjeta de crédito'), ('20', 'Otros con utilización del sistema financiero'), ('21', 'Endoso de títulos')], help_text='Selección obligatoria según tabla 24 SRI', max_length=2, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipoIdentificacion',
            field=models.CharField(choices=[('04', 'RUC'), ('05', 'Cédula'), ('06', 'Pasaporte'), ('07', 'Consumidor Final'), ('08', 'Identificación del Exterior')], max_length=2),
        ),
    ]
