# Generated by Django 5.1.3 on 2025-08-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventario",
            "0074_alter_factura_estado_sri_alter_formapago_forma_pago_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="formapago",
            name="caja",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="formas_pago",
                to="inventario.caja",
                verbose_name="Caja",
            ),
        ),
    ]
