# Generated by Django 5.1.3 on 2025-08-29 16:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0075_alter_formapago_caja"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ruc",
                    models.CharField(
                        max_length=13,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{13}$", "El RUC debe tener exactamente 13 dígitos"
                            )
                        ],
                    ),
                ),
                ("razon_social", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.empresa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "empresa")},
            },
        ),
        migrations.AddField(
            model_name="usuario",
            name="empresas",
            field=models.ManyToManyField(
                blank=True,
                related_name="usuarios",
                through="inventario.UsuarioEmpresa",
                to="inventario.empresa",
            ),
        ),
    ]
