# Generated by Django 5.1.3 on 2025-09-01 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0076_empresa_usuarioempresa_usuario_empresas"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientes",
                to="inventario.empresa",
            ),
        ),
        migrations.AddField(
            model_name="detallefactura",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_factura",
                to="inventario.empresa",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facturas",
                to="inventario.empresa",
            ),
        ),
        migrations.AddField(
            model_name="opciones",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opciones",
                to="inventario.empresa",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos",
                to="inventario.empresa",
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="inventario.empresa",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proveedores",
                to="inventario.empresa",
            ),
        ),
    ]
