# Generated by Django 5.1.3 on 2025-09-01 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0078_almacen_empresa_banco_empresa_caja_empresa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientes",
                to="inventario.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facturas",
                to="inventario.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="inventario.empresa",
            ),
        ),
    ]
