# Generated by Django 5.1.3 on 2025-09-02 16:07

from django.db import migrations, models
from django.contrib.auth.hashers import make_password, identify_hasher


def migrate_passwords(apps, schema_editor):
    Usuario = apps.get_model("inventario", "Usuario")
    for usuario in Usuario.objects.all():
        pwd = usuario.password
        if not pwd:
            usuario.set_unusable_password()
            usuario.save(update_fields=["password"])
            continue
        try:
            identify_hasher(pwd)
        except Exception:
            usuario.password = make_password(pwd)
            usuario.save(update_fields=["password"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0079_alter_cliente_empresa_alter_factura_empresa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.RunPython(migrate_passwords, migrations.RunPython.noop),
    ]
