# Generated by Django 5.2.5 on 2025-09-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0080_alter_usuario_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="identificacion",
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name="factura",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.cliente"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.proveedor"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="codigo",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="identificacion_proveedor",
            field=models.CharField(max_length=13),
        ),
        migrations.AddConstraint(
            model_name="cliente",
            constraint=models.UniqueConstraint(
                fields=("empresa", "identificacion"),
                name="unique_identificacion_por_empresa",
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.UniqueConstraint(
                fields=("empresa", "codigo"), name="unique_codigo_por_empresa"
            ),
        ),
        migrations.AddConstraint(
            model_name="proveedor",
            constraint=models.UniqueConstraint(
                fields=("empresa", "identificacion_proveedor"),
                name="unique_proveedor_por_empresa",
            ),
        ),
    ]
