# Generated by Django 5.1.3 on 2025-09-02 16:50

import inventario.crypto_utils
from django.db import migrations


def encrypt_passwords(apps, schema_editor):
    Opciones = apps.get_model("inventario", "Opciones")
    for opcion in Opciones.objects.exclude(password_firma__isnull=True).exclude(password_firma=""):
        opcion.password_firma = opcion.password_firma
        opcion.save(update_fields=["password_firma"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventario",
            "0081_alter_cliente_identificacion_alter_factura_cliente_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="opciones",
            name="password_firma",
            field=inventario.crypto_utils.EncryptedCharField(
                blank=True,
                help_text="Contraseña de la firma electrónica (almacenada cifrada).",
                max_length=500,
                null=True,
            ),
        ),
        migrations.RunPython(encrypt_passwords, migrations.RunPython.noop),
    ]
