# Generated by Django 5.2.5 on 2025-09-03 20:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0082_alter_opciones_password_firma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número de proforma (ej: PF-000001)', max_length=20)),
                ('fecha_emision', models.DateField(help_text='Fecha de emisión de la proforma')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento de la cotización')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones o condiciones de la proforma', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Subtotal sin impuestos', max_digits=20)),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0.0, help_text='Total de descuentos aplicados', max_digits=20)),
                ('total_impuestos', models.DecimalField(decimal_places=2, default=0.0, help_text='Total de impuestos (IVA)', max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total final de la proforma', max_digits=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CONVERTIDA', 'Convertida a Factura'), ('VENCIDA', 'Vencida')], default='BORRADOR', help_text='Estado actual de la proforma', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(blank=True, help_text='Almacén desde donde se cotiza', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.almacen')),
                ('cliente', models.ForeignKey(help_text='Cliente al que se dirige la proforma', on_delete=django.db.models.deletion.CASCADE, to='inventario.cliente')),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó la proforma', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proformas', to='inventario.empresa')),
                ('factura', models.OneToOneField(blank=True, help_text='Factura generada a partir de esta proforma', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.factura')),
                ('facturador', models.ForeignKey(help_text='Facturador que emite la proforma', on_delete=django.db.models.deletion.PROTECT, related_name='proformas', to='inventario.facturador')),
            ],
            options={
                'verbose_name': 'Proforma',
                'verbose_name_plural': 'Proformas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProformaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Cantidad de productos/servicios', validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto/servicio', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal (cantidad x precio unitario)', max_digits=20)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento monetario aplicado', max_digits=20)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento aplicado', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total', models.DecimalField(decimal_places=2, help_text='Total del detalle (subtotal - descuento + impuestos)', max_digits=20)),
                ('producto', models.ForeignKey(blank=True, help_text='Producto cotizado', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('proforma', models.ForeignKey(help_text='Proforma a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.proforma')),
                ('servicio', models.ForeignKey(blank=True, help_text='Servicio cotizado', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Proforma',
                'verbose_name_plural': 'Detalles de Proforma',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='proforma',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero'), name='unique_numero_proforma_por_empresa'),
        ),
    ]
