# Generated by Django 5.2.5 on 2025-09-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0083_proforma_proformadetalle_and_more'),
    ]

    operations = [
    ]
