# Generated by Django 5.2.5 on 2025-09-05 16:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0084_auto_20250903_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGuiaRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento_defecto', models.CharField(default='001', help_text='Establecimiento por defecto para nuevas guías', max_length=3)),
                ('punto_emision_defecto', models.CharField(default='001', help_text='Punto de emisión por defecto para nuevas guías', max_length=3)),
                ('nombre_comercial', models.CharField(blank=True, help_text='Nombre comercial para los documentos', max_length=300)),
                ('direccion_matriz', models.TextField(blank=True, help_text='Dirección de la matriz para las guías')),
                ('ambiente_sri', models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', help_text='Ambiente del SRI', max_length=1)),
                ('tipo_emision', models.CharField(choices=[('1', 'Emisión Normal'), ('2', 'Emisión por Indisponibilidad')], default='1', help_text='Tipo de emisión', max_length=1)),
                ('mostrar_logo', models.BooleanField(default=True, help_text='Mostrar logo en el PDF')),
                ('ruta_logo', models.CharField(blank=True, help_text='Ruta del archivo de logo', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Guías de Remisión',
                'verbose_name_plural': 'Configuraciones de Guías de Remisión',
                'db_table': 'configuracion_guia_remision',
            },
        ),
        migrations.CreateModel(
            name='GuiaRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.CharField(default='001', help_text='Código del establecimiento (3 dígitos)', max_length=3)),
                ('punto_emision', models.CharField(default='001', help_text='Código del punto de emisión (3 dígitos)', max_length=3)),
                ('secuencial', models.CharField(help_text='Número secuencial (9 dígitos)', max_length=9)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, help_text='Fecha de emisión de la guía')),
                ('fecha_inicio_traslado', models.DateTimeField(help_text='Fecha y hora de inicio del traslado')),
                ('fecha_fin_traslado', models.DateTimeField(blank=True, help_text='Fecha y hora de fin del traslado', null=True)),
                ('motivo_traslado', models.CharField(choices=[('01', 'Venta'), ('02', 'Transformación'), ('03', 'Consignación'), ('04', 'Devolución'), ('05', 'Otros')], help_text='Motivo del traslado según catálogo SRI', max_length=2)),
                ('destinatario_identificacion', models.CharField(help_text='RUC, cédula o pasaporte del destinatario', max_length=13)),
                ('destinatario_nombre', models.CharField(help_text='Razón social o nombre del destinatario', max_length=300)),
                ('direccion_partida', models.TextField(help_text='Dirección desde donde se envía la mercadería')),
                ('direccion_destino', models.TextField(help_text='Dirección donde se entrega la mercadería')),
                ('transportista_ruc', models.CharField(help_text='RUC del transportista', max_length=13)),
                ('transportista_nombre', models.CharField(help_text='Razón social del transportista', max_length=300)),
                ('placa', models.CharField(help_text='Placa del vehículo', max_length=10)),
                ('transportista_observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del transportista')),
                ('clave_acceso', models.CharField(blank=True, help_text='Clave de acceso SRI (49 dígitos)', max_length=49, null=True, unique=True)),
                ('numero_autorizacion', models.CharField(blank=True, help_text='Número de autorización del SRI', max_length=37, null=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, help_text='Fecha y hora de autorización del SRI', null=True)),
                ('xml_autorizado', models.TextField(blank=True, help_text='XML autorizado por el SRI', null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('autorizada', 'Autorizada'), ('anulada', 'Anulada'), ('devuelta', 'Devuelta')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales de la guía')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_creadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guía de Remisión',
                'verbose_name_plural': 'Guías de Remisión',
                'db_table': 'guia_remision',
                'ordering': ['-fecha_emision', '-secuencial'],
            },
        ),
        migrations.CreateModel(
            name='DetalleGuiaRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden del producto en la guía')),
                ('codigo_producto', models.CharField(help_text='Código del producto o servicio', max_length=50)),
                ('descripcion_producto', models.CharField(help_text='Descripción del producto o servicio', max_length=500)),
                ('cantidad', models.DecimalField(decimal_places=4, help_text='Cantidad del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unidad_medida', models.CharField(blank=True, help_text='Unidad de medida (kg, unidades, etc.)', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones específicas del producto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('guia', models.ForeignKey(help_text='Guía de remisión a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.guiaremision')),
            ],
            options={
                'verbose_name': 'Detalle de Guía de Remisión',
                'verbose_name_plural': 'Detalles de Guías de Remisión',
                'db_table': 'detalle_guia_remision',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='guiaremision',
            index=models.Index(fields=['fecha_emision'], name='guia_remisi_fecha_e_14d07c_idx'),
        ),
        migrations.AddIndex(
            model_name='guiaremision',
            index=models.Index(fields=['estado'], name='guia_remisi_estado_d2e7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='guiaremision',
            index=models.Index(fields=['destinatario_identificacion'], name='guia_remisi_destina_417d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='guiaremision',
            index=models.Index(fields=['clave_acceso'], name='guia_remisi_clave_a_15b72e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guiaremision',
            unique_together={('establecimiento', 'punto_emision', 'secuencial')},
        ),
        migrations.AddIndex(
            model_name='detalleguiaremision',
            index=models.Index(fields=['guia', 'orden'], name='detalle_gui_guia_id_e783e1_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleguiaremision',
            index=models.Index(fields=['codigo_producto'], name='detalle_gui_codigo__4055d4_idx'),
        ),
    ]
