# Generated by Django 5.1.3 on 2025-09-06 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0085_configuracionguiaremision_guiaremision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='inventario.cliente', to_field='identificacion'),
        ),
    ]
