# Generated by Django 5.1.3 on 2025-09-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0086_alter_cliente_identificacion_alter_factura_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.cliente"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="identificacion",
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="codigo",
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name="servicio",
            constraint=models.UniqueConstraint(
                fields=("empresa", "codigo"), name="unique_codigo_servicio_por_empresa"
            ),
        ),
    ]
