# Generated by Django 5.1.3 on 2025-09-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventario",
            "0087_alter_cliente_identificacion_alter_factura_cliente_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="tipo_ambiente",
            field=models.CharField(
                choices=[("1", "Pruebas"), ("2", "Producción")],
                default="1",
                help_text="Ambiente: 1=Pruebas, 2=Producción",
                max_length=1,
            ),
        ),
    ]
