# Generated by Django 5.1.3 on 2025-09-08 17:41

import inventario.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0088_empresa_tipo_ambiente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facturador",
            name="password",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="opciones",
            name="firma_electronica",
            field=models.FileField(
                blank=True,
                help_text="Archivo de firma electrónica (.p12 o .pfx). Se almacena cifrado y nunca se expone públicamente.",
                null=True,
                storage=inventario.storage.EncryptedFirmaStorage(),
                upload_to="firmas/",
            ),
        ),
    ]
