# Generated by Django 5.1.3 on 2025-09-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0089_alter_facturador_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opciones",
            name="correo",
            field=models.EmailField(
                default="pendiente@empresa.com",
                help_text="Email principal de su empresa",
                max_length=100,
            ),
        ),
    ]
