# Generated by Django 5.1.3 on 2025-09-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0090_alter_opciones_correo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opciones",
            options={
                "verbose_name": "Configuración de Empresa",
                "verbose_name_plural": "Configuración de Empresa",
            },
        ),
        migrations.RemoveField(
            model_name="opciones",
            name="valor_iva",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="iva",
        ),
    ]
