# Generated by Django 5.1.3 on 2025-09-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0092_usuarioempresa_overrides'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='secuencia',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.IntegerField(choices=[(2, 'Raíz'), (1, 'Administrador'), (0, 'Usuario')], default=0),
        ),
        migrations.AddConstraint(
            model_name='secuencia',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_documento', 'establecimiento', 'punto_emision'), name='uniq_secuencia_empresa_doc_estab_punto'),
        ),
    ]
