# Generated by Django 5.1.3 on 2025-10-01 18:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0094_factura_email_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('establecimiento', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('punto_emision', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('secuencia', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)])),
                ('concepto', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('sustento_tributario', models.CharField(choices=[('01', 'Crédito tributario para declaraciones'), ('02', 'Gasto personal'), ('03', 'Activo fijo'), ('04', 'Gasto general'), ('05', 'Inventarios'), ('06', 'Exportaciones'), ('07', 'Otros')], default='01', max_length=2)),
                ('total_sin_impuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_con_impuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('importe_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('propina', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('moneda', models.CharField(choices=[('DOLAR', 'Dólar (USD)'), ('EUR', 'Euro')], default='DOLAR', max_length=10)),
                ('clave_acceso', models.CharField(blank=True, max_length=49, null=True, unique=True)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=49, null=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('LISTA', 'Lista para firma'), ('FIRMADA', 'Firmada'), ('ENVIADA', 'Enviada al SRI'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=15)),
                ('estado_sri', models.CharField(choices=[('', 'No enviada'), ('PENDIENTE', 'Pendiente'), ('RECIBIDA', 'Recibida'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada'), ('ERROR', 'Error')], default='', max_length=15)),
                ('mensaje_sri', models.TextField(blank=True, null=True)),
                ('xml_firmado', models.TextField(blank=True, null=True)),
                ('xml_autorizado', models.TextField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_compra', to='inventario.almacen')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones_compra', to='inventario.empresa')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_compra', to='inventario.proveedor')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_emitidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha_emision', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LiquidacionCampoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('valor', models.CharField(max_length=300)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_adicionales', to='inventario.liquidacioncompra')),
            ],
            options={
                'verbose_name': 'Campo Adicional de Liquidación',
                'verbose_name_plural': 'Campos Adicionales de Liquidación',
            },
        ),
        migrations.CreateModel(
            name='LiquidacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('costo', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('precio_total_sin_impuesto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.liquidacioncompra')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Liquidación',
                'verbose_name_plural': 'Detalles de Liquidación',
            },
        ),
        migrations.CreateModel(
            name='LiquidacionDetalleImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=1)),
                ('codigo_porcentaje', models.CharField(max_length=4)),
                ('tarifa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='inventario.liquidaciondetalle')),
            ],
            options={
                'verbose_name': 'Impuesto de Detalle',
                'verbose_name_plural': 'Impuestos de Detalle',
            },
        ),
        migrations.CreateModel(
            name='LiquidacionFormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(choices=[('01', 'Sin utilización del sistema financiero'), ('15', 'Compensación de deudas'), ('16', 'Tarjeta de débito'), ('17', 'Dinero electrónico'), ('18', 'Tarjeta prepago'), ('19', 'Tarjeta de crédito'), ('20', 'Otros con utilización del sistema financiero'), ('21', 'Endoso de títulos')], max_length=2)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('plazo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('unidad_tiempo', models.CharField(blank=True, max_length=10, null=True)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pago', to='inventario.liquidacioncompra')),
            ],
            options={
                'verbose_name': 'Forma de Pago de Liquidación',
                'verbose_name_plural': 'Formas de Pago de Liquidación',
            },
        ),
        migrations.CreateModel(
            name='LiquidacionLogCambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('LISTA', 'Lista para firma'), ('FIRMADA', 'Firmada'), ('ENVIADA', 'Enviada al SRI'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada'), ('ANULADA', 'Anulada')], max_length=15)),
                ('estado_sri', models.CharField(blank=True, choices=[('', 'No enviada'), ('PENDIENTE', 'Pendiente'), ('RECIBIDA', 'Recibida'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada'), ('ERROR', 'Error')], max_length=15)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='inventario.liquidacioncompra')),
            ],
            options={
                'verbose_name': 'Historial de Liquidación',
                'verbose_name_plural': 'Historial de Liquidaciones',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='LiquidacionTotalImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=1)),
                ('codigo_porcentaje', models.CharField(max_length=4)),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('descuento_adicional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totales_impuestos', to='inventario.liquidacioncompra')),
            ],
            options={
                'verbose_name': 'Total de Impuesto',
                'verbose_name_plural': 'Totales de Impuesto',
            },
        ),
        migrations.AddIndex(
            model_name='liquidacioncompra',
            index=models.Index(fields=['empresa', 'fecha_emision'], name='inventario__empresa_cc0408_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacioncompra',
            index=models.Index(fields=['empresa', 'estado'], name='inventario__empresa_aa862d_idx'),
        ),
        migrations.AddConstraint(
            model_name='liquidacioncompra',
            constraint=models.UniqueConstraint(fields=('empresa', 'establecimiento', 'punto_emision', 'secuencia'), name='uniq_liquidacion_empresa_serie_sec'),
        ),
        migrations.AlterUniqueTogether(
            name='liquidacionformapago',
            unique_together={('liquidacion', 'forma_pago')},
        ),
    ]
