# Generated by Django 5.1.3 on 2025-10-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0095_alter_opciones_firma_electronica_liquidacioncompra_and_more'),
    ]

    operations = []
