# Generated by Django 5.1.3 on 2025-10-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0096_alter_opciones_firma_electronica'),
    ]

    operations = []
