# Generated by Django 5.1.3 on 2025-10-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0098_prestador'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='prestador',
            new_name='inventario__identif_93ff19_idx',
            old_name='inventario_identifi_60b0e6_idx',
        ),
        migrations.RenameIndex(
            model_name='prestador',
            new_name='inventario__tipo_id_82276b_idx',
            old_name='inventario_tipo_id_7284f2_idx',
        ),
        migrations.RenameIndex(
            model_name='prestador',
            new_name='inventario__empresa_929289_idx',
            old_name='inventario_empresas_4f6988_idx',
        ),
    ]
