# Generated by Django 5.1.3 on 2025-10-08 22:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0099_rename_inventario_identifi_60b0e6_idx_inventario__identif_93ff19_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacioncompra',
            name='base_exenta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='liquidacioncompra',
            name='base_imponible_cero',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='liquidacioncompra',
            name='base_imponible_gravada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='liquidacioncompra',
            name='base_imponible_reducida',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='liquidacioncompra',
            name='base_no_objeto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='liquidacioncompra',
            name='iva_presuntivo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='liquidacioncompra',
            name='retencion_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='liquidacioncompra',
            name='retencion_iva_porcentaje',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5),
        ),
        migrations.AddField(
            model_name='liquidacioncompra',
            name='retencion_renta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='liquidacioncompra',
            name='retencion_renta_porcentaje',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5),
        ),
        migrations.AddField(
            model_name='liquidacioncompra',
            name='total_cantidad',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='liquidacioncompra',
            name='total_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liquidacioncompra',
            name='valor_total_ice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='liquidacioncompra',
            name='valor_total_irbp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='liquidacioncompra',
            name='valor_total_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='codigo_iva',
            field=models.CharField(blank=True, default='2', max_length=4),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='precio_unitario_con_impuestos',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='tarifa_iva',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='total_con_impuestos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='valor_ice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='valor_irbp',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='liquidaciondetalle',
            name='valor_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
