# Generated by Django 5.1.3 on 2025-10-13 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0100_liquidacioncompra_base_exenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacioncompra',
            name='autorizacion',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='La autorización solo puede contener letras, números, espacios o guiones.', regex='^[0-9A-Za-z\\s\\-]+$')]),
        ),
        migrations.AddField(
            model_name='liquidacioncompra',
            name='tipo_liquidacion',
            field=models.CharField(choices=[('001901', '001901 Liquidación de Compra Electrónica')], default='001901', max_length=6),
        ),
    ]
