# Generated by Django 5.1.3 on 2025-10-21 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0101_liquidacioncompra_autorizacion_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="guiaremision",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="detalleguiaremision",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_guia_remision",
                to="inventario.empresa",
            ),
        ),
        migrations.AddField(
            model_name="guiaremision",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guias_remision",
                to="inventario.empresa",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="guiaremision",
            unique_together={
                ("empresa", "establecimiento", "punto_emision", "secuencial")
            },
        ),
    ]
