# Generated by Django 5.1.3 on 2025-10-21 21:38

import django.db.models.deletion
from django.db import migrations, models


def asignar_empresa_por_defecto(apps, schema_editor):
    """
    Asigna la primera empresa disponible a todas las guías de remisión
    que no tengan empresa asignada.
    """
    GuiaRemision = apps.get_model('inventario', 'GuiaRemision')
    Empresa = apps.get_model('inventario', 'Empresa')
    
    # Obtener la primera empresa disponible
    primera_empresa = Empresa.objects.first()
    
    if primera_empresa:
        # Actualizar todas las guías sin empresa
        GuiaRemision.objects.filter(empresa__isnull=True).update(
            empresa=primera_empresa
        )


def revertir_asignacion(apps, schema_editor):
    """
    Función de reversión (opcional, no hace nada en este caso)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0102_alter_guiaremision_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(asignar_empresa_por_defecto, revertir_asignacion),
        migrations.AlterField(
            model_name='guiaremision',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias_remision', to='inventario.empresa'),
        ),
    ]
