# Generated by Django 5.1.3 on 2025-10-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0103_add_empresa_to_guia_remision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guiaremision',
            options={'ordering': ['-fecha_inicio_traslado', '-secuencial'], 'verbose_name': 'Guía de Remisión', 'verbose_name_plural': 'Guías de Remisión'},
        ),
        migrations.RemoveIndex(
            model_name='guiaremision',
            name='guia_remisi_fecha_e_14d07c_idx',
        ),
        migrations.RemoveIndex(
            model_name='guiaremision',
            name='guia_remisi_destina_417d1c_idx',
        ),
        migrations.RemoveField(
            model_name='guiaremision',
            name='destinatario_identificacion',
        ),
        migrations.RemoveField(
            model_name='guiaremision',
            name='destinatario_nombre',
        ),
        migrations.RemoveField(
            model_name='guiaremision',
            name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='guiaremision',
            name='motivo_traslado',
        ),
        migrations.RemoveField(
            model_name='guiaremision',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='guiaremision',
            name='transportista_observaciones',
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='clave_acceso',
            field=models.CharField(blank=True, max_length=49, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='direccion_destino',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='direccion_partida',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='establecimiento',
            field=models.CharField(default='001', max_length=3),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('autorizada', 'Autorizada'), ('anulada', 'Anulada')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='fecha_fin_traslado',
            field=models.DateField(blank=True, help_text='Fecha de llegada', null=True),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='fecha_inicio_traslado',
            field=models.DateField(help_text='Fecha de salida'),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='numero_autorizacion',
            field=models.CharField(blank=True, max_length=37, null=True),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='placa',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='punto_emision',
            field=models.CharField(default='001', max_length=3),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='secuencial',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='transportista_nombre',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='transportista_ruc',
            field=models.CharField(help_text='Cédula o RUC del transportista', max_length=13),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='xml_autorizado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='guiaremision',
            index=models.Index(fields=['fecha_inicio_traslado'], name='guia_remisi_fecha_i_332143_idx'),
        ),
    ]
