# Generated by Django 5.1.3 on 2025-10-22 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0104_simplificar_guia_remision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc_cedula', models.CharField(help_text='Cédula o RUC del transportista', max_length=13)),
                ('nombre', models.CharField(max_length=300)),
                ('direccion', models.TextField(blank=True, default='')),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('placa_principal', models.CharField(blank=True, default='', help_text='Placa del vehículo principal', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportistas', to='inventario.empresa')),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
                'db_table': 'transportista',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['ruc_cedula'], name='transportis_ruc_ced_9cd314_idx'), models.Index(fields=['nombre'], name='transportis_nombre_69e819_idx'), models.Index(fields=['activo'], name='transportis_activo_a735a3_idx')],
                'unique_together': {('empresa', 'ruc_cedula')},
            },
        ),
    ]
