# Generated by Django 5.1.3 on 2025-10-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0105_transportista'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaremision',
            name='correo_envio',
            field=models.EmailField(blank=True, default='', help_text='Correo para envío del documento', max_length=254),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='informacion_adicional',
            field=models.TextField(blank=True, default='', help_text='Información adicional del traslado'),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='ruta',
            field=models.TextField(blank=True, default='', help_text='Ruta del traslado'),
        ),
    ]
