# Generated by Django 5.1.3 on 2025-10-22 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0106_guiaremision_correo_envio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinatarioGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion_destinatario', models.CharField(help_text='RUC, cédula o pasaporte del destinatario', max_length=20)),
                ('razon_social_destinatario', models.CharField(help_text='Nombre o razón social del destinatario', max_length=300)),
                ('dir_destinatario', models.CharField(help_text='Dirección del destinatario', max_length=300)),
                ('motivo_traslado', models.CharField(help_text='Motivo del traslado de mercadería', max_length=300)),
                ('cod_doc_sustento', models.CharField(blank=True, help_text='Código del documento sustento (01=Factura, etc.)', max_length=2)),
                ('num_doc_sustento', models.CharField(blank=True, help_text='Número del documento sustento (000-000-000000000)', max_length=17)),
                ('num_aut_doc_sustento', models.CharField(blank=True, help_text='Número de autorización del documento sustento', max_length=49)),
                ('fecha_emision_doc_sustento', models.DateField(blank=True, help_text='Fecha de emisión del documento sustento', null=True)),
                ('doc_aduanero_unico', models.CharField(blank=True, help_text='Documento aduanero único', max_length=20)),
                ('cod_estab_destino', models.CharField(blank=True, default='001', help_text='Código de establecimiento de destino', max_length=3)),
                ('ruta', models.CharField(blank=True, help_text='Ruta específica para este destinatario', max_length=300)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='inventario.guiaremision')),
            ],
            options={
                'verbose_name': 'Destinatario de Guía',
                'verbose_name_plural': 'Destinatarios de Guías',
                'db_table': 'destinatario_guia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDestinatarioGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(help_text='Código interno del producto', max_length=25)),
                ('codigo_adicional', models.CharField(blank=True, help_text='Código adicional del producto', max_length=25)),
                ('descripcion', models.CharField(help_text='Descripción del producto', max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=6, help_text='Cantidad del producto', max_digits=14)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.destinatarioguia')),
            ],
            options={
                'verbose_name': 'Detalle de Destinatario',
                'verbose_name_plural': 'Detalles de Destinatarios',
                'db_table': 'detalle_destinatario_guia',
                'ordering': ['id'],
            },
        ),
    ]
