# Generated by Django 5.1.3 on 2025-10-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0107_destinatarioguia_detalledestinatarioguia'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaremision',
            name='contribuyente_especial',
            field=models.CharField(blank=True, default='', help_text='Número de resolución de contribuyente especial', max_length=13),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='dir_establecimiento',
            field=models.CharField(blank=True, default='', help_text='Dirección del establecimiento que emite la guía', max_length=300),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='obligado_contabilidad',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO'), ('', 'N/A')], default='', help_text='¿Obligado a llevar contabilidad?', max_length=2),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='rise',
            field=models.CharField(blank=True, default='', help_text='Régimen RISE del transportista (si aplica)', max_length=40),
        ),
        migrations.AddField(
            model_name='guiaremision',
            name='tipo_identificacion_transportista',
            field=models.CharField(choices=[('04', 'RUC'), ('05', 'Cédula'), ('06', 'Pasaporte'), ('07', 'Consumidor Final'), ('08', 'Identificación del exterior')], default='05', help_text='Tipo de identificación del transportista (04-08)', max_length=2),
        ),
    ]
