# Generated by Django 5.1.3 on 2025-10-22 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0108_agregar_campos_sri_guia_corregido'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaremision',
            name='factura',
            field=models.ForeignKey(blank=True, help_text='Factura asociada (obligatorio cuando motivo es venta)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_remision', to='inventario.factura'),
        ),
    ]
