# Generated by Django 5.1.3 on 2025-11-06 22:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0109_add_factura_to_guia_remision"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="creada_en",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="empresa",
            name="creada_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empresas_creadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
