# Generated by Django 5.1.3 on 2025-11-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0112_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='fecha_apertura',
            field=models.DateField(blank=True, help_text='Fecha en que se abrió la cuenta', null=True, verbose_name='Fecha Apertura'),
        ),
    ]
