# Generated by Django 5.1.3

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0113_alter_banco_fecha_apertura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opciones',
            name='mensaje_factura',
        ),
        migrations.RemoveField(
            model_name='opciones',
            name='nombre_negocio',
        ),
    ]
