# Generated by Django 5.1.3 on 2025-11-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0113_alter_banco_fecha_apertura'),
    ]

    operations = [
    ]
