# Generated by Django 5.1.3 on 2025-11-28 22:10

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0115_fix_numero_autorizacion_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('MICRO', 'Plan Micro'), ('BASICO', 'Plan Básico'), ('EMPRENDEDOR', 'Plan Emprendedor'), ('EXTRA', 'Opción Extra')], max_length=20, unique=True, verbose_name='Código del Plan')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Base (sin IVA)')),
                ('limite_documentos', models.PositiveIntegerField(help_text='Número máximo de documentos que se pueden autorizar al mes/año', verbose_name='Límite de Documentos')),
                ('frecuencia', models.CharField(choices=[('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], default='ANUAL', max_length=20, verbose_name='Frecuencia de Cobro')),
                ('activo', models.BooleanField(default=True, verbose_name='Plan Activo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Plan de Facturación',
                'verbose_name_plural': 'Planes de Facturación',
                'ordering': ['precio_base'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('documentos_autorizados', models.PositiveIntegerField(default=0, verbose_name='Documentos Autorizados en el Periodo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_planes', to='inventario.empresa', verbose_name='Empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Historial de Plan',
                'verbose_name_plural': 'Historial de Planes',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.date.today, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Se calcula automáticamente según la frecuencia del plan', null=True, verbose_name='Fecha de Finalización')),
                ('documentos_autorizados', models.PositiveIntegerField(default=0, help_text='Contador de documentos autorizados en el periodo actual', verbose_name='Documentos Autorizados')),
                ('ultimo_reset', models.DateField(default=datetime.date.today, help_text='Última vez que se reinició el contador', verbose_name='Último Reseteo')),
                ('notificacion_enviada', models.BooleanField(default=False, help_text='Se envió notificación al alcanzar el 80% del límite', verbose_name='Notificación Enviada')),
                ('activo', models.BooleanField(default=True, verbose_name='Plan Activo')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_activo', to='inventario.empresa', verbose_name='Empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='inventario.plan', verbose_name='Plan Actual')),
            ],
            options={
                'verbose_name': 'Plan de Empresa',
                'verbose_name_plural': 'Planes de Empresas',
            },
        ),
    ]
