# Generated by Django 5.1.3 on 2025-12-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0116_plan_remove_opciones_mensaje_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='codigo_personalizado',
            field=models.CharField(blank=True, help_text='Código personalizado para esta factura (si difiere del producto)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='iva_codigo',
            field=models.CharField(blank=True, help_text='Código de IVA personalizado para esta factura (0, 2, 4, 5, etc.)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Precio unitario personalizado para esta factura', max_digits=18, null=True),
        ),
    ]
