# Generated by Django 5.1.3 on 2025-12-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0117_add_custom_fields_detallefactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiene_inventario',
            field=models.BooleanField(default=False, help_text='Si está marcado, se descontará del inventario al facturar'),
        ),
    ]
