# Generated by Django 5.1.3 on 2025-12-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0118_add_tiene_inventario_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='descripcion_reemplazo',
            field=models.CharField(blank=True, help_text='Descripción que reemplaza a la del producto en esta factura', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='info_adicional',
            field=models.TextField(blank=True, help_text='Información adicional que aparece en detallesAdicionales del XML SRI', max_length=300, null=True),
        ),
    ]
