# Generated by Django 5.1.3 on 2025-06-01 12:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0119_add_info_adicional_detallefactura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Datos del comprobante
                ('establecimiento', models.CharField(default='001', help_text='Código del establecimiento (3 dígitos)', max_length=3)),
                ('punto_emision', models.CharField(default='001', help_text='Punto de emisión (3 dígitos)', max_length=3)),
                ('secuencial', models.CharField(help_text='Número secuencial (9 dígitos)', max_length=9)),
                # Clave de acceso y autorización
                ('clave_acceso', models.CharField(blank=True, help_text='Clave de acceso de 49 dígitos', max_length=49, null=True, unique=True)),
                ('numero_autorizacion', models.CharField(blank=True, help_text='Número de autorización del SRI', max_length=49, null=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, help_text='Fecha y hora de autorización', null=True)),
                # Fechas
                ('fecha_emision', models.DateField(help_text='Fecha de emisión de la nota de crédito')),
                # Datos del documento modificado
                ('cod_doc_modificado', models.CharField(default='01', help_text='Código del documento modificado (01=Factura)', max_length=2)),
                ('num_doc_modificado', models.CharField(help_text='Número completo del documento: 001-001-000000001', max_length=17)),
                ('fecha_emision_doc_sustento', models.DateField(help_text='Fecha de emisión de la factura original')),
                # Motivo
                ('tipo_motivo', models.CharField(choices=[('DEVOLUCION', 'Devolución de mercadería'), ('DESCUENTO', 'Descuento posterior a la venta'), ('ANULACION', 'Anulación de factura'), ('CORRECCION', 'Corrección de valores'), ('OTRO', 'Otro motivo')], default='DEVOLUCION', max_length=20)),
                ('motivo', models.CharField(help_text='Descripción del motivo de la nota de crédito', max_length=300)),
                # Valores monetarios
                ('subtotal_sin_impuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal sin impuestos', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal_iva_0', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal con IVA 0%', max_digits=14)),
                ('subtotal_iva_5', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal con IVA 5%', max_digits=14)),
                ('subtotal_iva_12', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal con IVA 12%', max_digits=14)),
                ('subtotal_iva_15', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal con IVA 15%', max_digits=14)),
                ('subtotal_no_objeto_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal no objeto de IVA', max_digits=14)),
                ('subtotal_exento_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal exento de IVA', max_digits=14)),
                ('total_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total del IVA', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_modificacion', models.DecimalField(decimal_places=2, help_text='Valor total de la nota de crédito', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                # Observaciones
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', null=True)),
                # Estado
                ('estado_sri', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('AUTORIZADO', 'Autorizado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('mensaje_sri', models.TextField(blank=True, help_text='Mensaje de respuesta del SRI', null=True)),
                # Control de inventario
                ('inventario_actualizado', models.BooleanField(default=False, help_text='Indica si ya se actualizó el inventario (devoluciones)')),
                # Auditoría
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                # Foreign Keys
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='inventario.empresa')),
                ('factura_modificada', models.ForeignKey(help_text='Factura que se está modificando', on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='inventario.factura')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito_creadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['-fecha_emision', '-secuencial'],
                'unique_together': {('empresa', 'establecimiento', 'punto_emision', 'secuencial')},
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_principal', models.CharField(max_length=25)),
                ('codigo_auxiliar', models.CharField(blank=True, max_length=25, null=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('precio_unitario', models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('precio_total_sin_impuesto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('codigo_iva', models.CharField(default='2', help_text='Código de IVA: 0=0%, 2=12%, 3=14%, 4=15%, 5=5%, 6=No objeto, 7=Exento', max_length=2)),
                ('tarifa_iva', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('valor_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                # Foreign Keys
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.notacredito')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Nota de Crédito',
                'verbose_name_plural': 'Detalles de Nota de Crédito',
            },
        ),
        migrations.CreateModel(
            name='TotalImpuestoNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='2', help_text='Código del impuesto (2=IVA, 3=ICE, 5=IRBPNR)', max_length=2)),
                ('codigo_porcentaje', models.CharField(help_text='Código del porcentaje de IVA', max_length=4)),
                ('tarifa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                # Foreign Keys
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totales_impuestos', to='inventario.notacredito')),
            ],
            options={
                'verbose_name': 'Total Impuesto NC',
                'verbose_name_plural': 'Totales Impuestos NC',
            },
        ),
    ]
