# Generated by Django 5.1.3 on 2025-12-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0120_remove_opciones_mensaje_factura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opciones',
            name='mensaje_factura',
        ),
        migrations.RemoveField(
            model_name='opciones',
            name='nombre_negocio',
        ),
        migrations.AlterField(
            model_name='detallenotacredito',
            name='codigo_iva',
            field=models.CharField(default='4', help_text='Código de IVA: 0=0%, 2=12%, 3=14%, 4=15%, 5=5%, 6=No objeto, 7=Exento', max_length=2),
        ),
    ]
