# Generated by Django 5.1.3 on 2026-01-12 16:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0121_remove_opciones_mensaje_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado_sri',
            field=models.CharField(blank=True, choices=[('', 'Local - No enviado al SRI'), ('PENDIENTE', 'Pendiente'), ('RECIBIDA', 'Recibida por SRI'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada'), ('ERROR', 'Error en procesamiento'), ('ANULADA', 'Anulada')], default='', help_text='Estado de la factura en el SRI', max_length=20),
        ),
        migrations.CreateModel(
            name='NotaDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento', models.CharField(default='001', max_length=3)),
                ('punto_emision', models.CharField(default='001', max_length=3)),
                ('secuencial', models.CharField(max_length=9)),
                ('clave_acceso', models.CharField(blank=True, max_length=49, null=True, unique=True)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=49, null=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_emision', models.DateField()),
                ('cod_doc_modificado', models.CharField(default='01', max_length=2)),
                ('num_doc_modificado', models.CharField(max_length=17)),
                ('fecha_emision_doc_sustento', models.DateField()),
                ('motivo', models.CharField(max_length=300)),
                ('subtotal_sin_impuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_modificacion', models.DecimalField(decimal_places=2, help_text='Valor total de la nota de débito', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado_sri', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('AUTORIZADO', 'Autorizado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('mensaje_sri', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_debito_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_debito', to='inventario.empresa')),
                ('factura_modificada', models.ForeignKey(help_text='Factura que se está modificando', on_delete=django.db.models.deletion.PROTECT, related_name='notas_debito', to='inventario.factura')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_debito_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Débito',
                'verbose_name_plural': 'Notas de Débito',
                'ordering': ['-fecha_emision', '-secuencial'],
                'unique_together': {('empresa', 'establecimiento', 'punto_emision', 'secuencial')},
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_principal', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('codigo_iva', models.CharField(default='2', max_length=2)),
                ('tarifa_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_notas_debito', to='inventario.empresa')),
                ('nota_debito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.notadebito')),
            ],
            options={
                'verbose_name': 'Detalle Nota de Débito',
                'verbose_name_plural': 'Detalles Nota de Débito',
            },
        ),
        migrations.CreateModel(
            name='TotalImpuestoNotaDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='2', max_length=2)),
                ('codigo_porcentaje', models.CharField(default='2', max_length=2)),
                ('tarifa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('nota_debito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totales_impuestos', to='inventario.notadebito')),
            ],
            options={
                'verbose_name': 'Total Impuesto Nota de Débito',
                'verbose_name_plural': 'Totales Impuestos Nota de Débito',
            },
        ),
    ]
