# Generated by GitHub Copilot on 2026-02-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0123_empresaplan_notificacion_limite_enviada'),
    ]

    operations = [
        migrations.AddField(
            model_name='opciones',
            name='mensaje_en_facturas',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Mensaje opcional a imprimir en la factura/ticket (entre el nombre comercial y el RUC)',
                max_length=300,
            ),
        ),
    ]
