# Generated by GitHub Copilot on 2026-03-02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0124_opciones_mensaje_en_facturas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteRetencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('identificacion_sujeto', models.CharField(blank=True, default='', max_length=20)),
                ('razon_social_sujeto', models.CharField(blank=True, default='', max_length=300)),
                ('tipo_documento_sustento', models.CharField(choices=[('01', '(01) Factura'), ('03', '(03) Liquidación de Compra')], default='01', max_length=2)),
                ('establecimiento_doc', models.CharField(default='001', max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Debe tener 3 dígitos.')])),
                ('punto_emision_doc', models.CharField(default='001', max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Debe tener 3 dígitos.')])),
                ('secuencia_doc', models.CharField(default='000000001', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'Debe tener 9 dígitos.')])),
                ('autorizacion_doc_sustento', models.CharField(blank=True, default='', max_length=49)),
                ('forma_pago_sri', models.CharField(blank=True, default='20', max_length=5)),
                ('sustento_tributario', models.CharField(blank=True, default='00', max_length=5)),
                ('forma_pago', models.CharField(blank=True, default='EFECTIVO', max_length=20)),
                ('base_iva_0', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('base_iva_5', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('base_no_obj_iva', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('base_exento_iva', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('base_iva', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('monto_iva', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default='15.00', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('monto_ice', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('tipo_retencion', models.CharField(choices=[('001901', 'Retención Electrónica 001 901')], default='001901', max_length=6)),
                ('fecha_emision_retencion', models.DateField()),
                ('establecimiento_retencion', models.CharField(default='001', max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Debe tener 3 dígitos.')])),
                ('punto_emision_retencion', models.CharField(default='901', max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Debe tener 3 dígitos.')])),
                ('secuencia_retencion', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'Debe tener 9 dígitos.')])),
                ('autorizacion_retencion', models.CharField(blank=True, default='', max_length=49)),
                ('total_retencion_renta', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('total_retencion_iva', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('total_retenido', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('estado_sri', models.CharField(choices=[('', 'No enviada'), ('PENDIENTE', 'Pendiente'), ('RECIBIDA', 'Recibida'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada'), ('ERROR', 'Error')], default='', max_length=15)),
                ('numero_autorizacion', models.CharField(blank=True, default='', max_length=49)),
                ('clave_acceso', models.CharField(blank=True, default='', max_length=49)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones_emitidas', to='inventario.empresa')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retenciones', to='inventario.proveedor')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenciones_creadas', to='inventario.usuario')),
            ],
            options={
                'ordering': ('-fecha_emision_retencion', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RetencionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_impuesto', models.CharField(choices=[('RENTA', 'Renta'), ('IVA', 'IVA')], max_length=10)),
                ('codigo_retencion', models.CharField(max_length=10)),
                ('descripcion_retencion', models.CharField(blank=True, default='', max_length=255)),
                ('base_imponible', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('porcentaje_retener', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valor_retenido', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.comprobanteretencion')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='comprobanteretencion',
            index=models.Index(fields=['empresa', 'fecha_emision_retencion'], name='inventario_c_empresa_2662b2_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobanteretencion',
            index=models.Index(fields=['empresa', 'estado_sri'], name='inventario_c_empresa_9952ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='comprobanteretencion',
            constraint=models.UniqueConstraint(fields=('empresa', 'establecimiento_retencion', 'punto_emision_retencion', 'secuencia_retencion'), name='uniq_retencion_empresa_serie_sec'),
        ),
        migrations.AddIndex(
            model_name='retenciondetalle',
            index=models.Index(fields=['tipo_impuesto', 'codigo_retencion'], name='inventario_r_tipo_im_0f8ede_idx'),
        ),
    ]
