# Generated by GitHub Copilot on 2026-02-18

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0124_opciones_mensaje_en_facturas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetencionCompra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha_emision", models.DateField()),
                ("fecha_emision_doc_sustento", models.DateField()),
                (
                    "establecimiento",
                    models.PositiveSmallIntegerField(),
                ),
                (
                    "punto_emision",
                    models.PositiveSmallIntegerField(),
                ),
                (
                    "secuencia",
                    models.PositiveIntegerField(),
                ),
                (
                    "version_xml",
                    models.CharField(
                        choices=[("1.0.0", "Versión 1.0.0"), ("2.0.0", "Versión 2.0.0 ATS")],
                        default="2.0.0",
                        max_length=5,
                    ),
                ),
                (
                    "cod_doc_sustento",
                    models.CharField(
                        choices=[("01", "Factura"), ("03", "Liquidación de Compra"), ("04", "Nota de Crédito")],
                        default="01",
                        max_length=2,
                    ),
                ),
                ("num_doc_sustento", models.CharField(max_length=15)),
                ("num_aut_doc_sustento", models.CharField(blank=True, max_length=49, null=True)),
                (
                    "tipo_identificacion_sujeto_retenido",
                    models.CharField(
                        choices=[
                            ("04", "RUC"),
                            ("05", "Cédula"),
                            ("06", "Pasaporte"),
                            ("08", "Identificación del exterior"),
                        ],
                        max_length=2,
                    ),
                ),
                ("razon_social_sujeto_retenido", models.CharField(max_length=300)),
                ("identificacion_sujeto_retenido", models.CharField(max_length=13)),
                ("periodo_fiscal", models.CharField(blank=True, max_length=7)),
                ("total_sin_impuestos_doc", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20)),
                ("total_iva_doc", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20)),
                ("importe_total_doc", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20)),
                ("total_retenido_renta", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20)),
                ("total_retenido_iva", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20)),
                ("total_retenido", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20)),
                ("codigo_interno", models.CharField(blank=True, default="", max_length=8)),
                ("clave_acceso", models.CharField(blank=True, max_length=49, null=True, unique=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("LISTA", "Lista"),
                            ("FIRMADA", "Firmada"),
                            ("ENVIADA", "Enviada"),
                            ("AUTORIZADA", "Autorizada"),
                            ("RECHAZADA", "Rechazada"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="BORRADOR",
                        max_length=15,
                    ),
                ),
                (
                    "estado_sri",
                    models.CharField(
                        choices=[
                            ("", "No enviada"),
                            ("PENDIENTE", "Pendiente"),
                            ("RECIBIDA", "Recibida"),
                            ("AUTORIZADO", "Autorizado"),
                            ("NO AUTORIZADO", "No autorizado"),
                            ("RECHAZADA", "Rechazada"),
                            ("ERROR", "Error"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("mensaje_sri", models.TextField(blank=True, null=True)),
                ("numero_autorizacion", models.CharField(blank=True, max_length=49, null=True)),
                ("fecha_autorizacion", models.DateTimeField(blank=True, null=True)),
                ("xml_generado", models.TextField(blank=True, null=True)),
                ("xml_firmado", models.TextField(blank=True, null=True)),
                ("xml_autorizado", models.TextField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retenciones_compra",
                        to="inventario.empresa",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retenciones_compra",
                        to="inventario.proveedor",
                    ),
                ),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retenciones_emitidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-fecha_emision", "-id"),
            },
        ),
        migrations.CreateModel(
            name="RetencionCampoAdicional",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=300)),
                ("valor", models.CharField(max_length=300)),
                (
                    "retencion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campos_adicionales",
                        to="inventario.retencioncompra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campo adicional de retención",
                "verbose_name_plural": "Campos adicionales de retención",
            },
        ),
        migrations.CreateModel(
            name="RetencionImpuesto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("1", "Renta"),
                            ("2", "IVA"),
                            ("6", "ISD"),
                            ("4", "IVA Presuntivo/Renta"),
                        ],
                        max_length=1,
                    ),
                ),
                ("codigo_retencion", models.CharField(max_length=10)),
                ("base_imponible", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20)),
                ("porcentaje_retener", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=7)),
                ("valor_retenido", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20)),
                (
                    "retencion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impuestos",
                        to="inventario.retencioncompra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impuesto Retenido",
                "verbose_name_plural": "Impuestos Retenidos",
            },
        ),
        migrations.CreateModel(
            name="RetencionLogCambioEstado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("LISTA", "Lista"),
                            ("FIRMADA", "Firmada"),
                            ("ENVIADA", "Enviada"),
                            ("AUTORIZADA", "Autorizada"),
                            ("RECHAZADA", "Rechazada"),
                            ("ANULADA", "Anulada"),
                        ],
                        max_length=15,
                    ),
                ),
                ("estado_sri", models.CharField(blank=True, max_length=20)),
                ("mensaje", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "retencion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_estados",
                        to="inventario.retencioncompra",
                    ),
                ),
            ],
            options={
                "ordering": ("-creado_en",),
                "verbose_name": "Historial de retención",
                "verbose_name_plural": "Historial de retenciones",
            },
        ),
        migrations.AddIndex(
            model_name="retencioncompra",
            index=models.Index(fields=["empresa", "fecha_emision"], name="inventario__empresa__5ec5c6_idx"),
        ),
        migrations.AddIndex(
            model_name="retencioncompra",
            index=models.Index(fields=["empresa", "estado"], name="inventario__empresa__77f1f1_idx"),
        ),
        migrations.AddIndex(
            model_name="retencioncompra",
            index=models.Index(fields=["empresa", "estado_sri"], name="inventario__empresa__862665_idx"),
        ),
        migrations.AddConstraint(
            model_name="retencioncompra",
            constraint=models.UniqueConstraint(
                fields=("empresa", "establecimiento", "punto_emision", "secuencia"),
                name="uniq_retencion_empresa_serie_sec",
            ),
        ),
    ]
