# Generated by Django 5.1.3 on 2026-02-18 18:40

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0125_retenciones_compra_module'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='retencioncompra',
            new_name='inventario__empresa_8b6329_idx',
            old_name='inventario__empresa__5ec5c6_idx',
        ),
        migrations.RenameIndex(
            model_name='retencioncompra',
            new_name='inventario__empresa_76f948_idx',
            old_name='inventario__empresa__77f1f1_idx',
        ),
        migrations.RenameIndex(
            model_name='retencioncompra',
            new_name='inventario__empresa_5e92dc_idx',
            old_name='inventario__empresa__862665_idx',
        ),
        migrations.AlterField(
            model_name='retencioncompra',
            name='establecimiento',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='retencioncompra',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='retencioncompra',
            name='fecha_emision_doc_sustento',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='retencioncompra',
            name='punto_emision',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='retencioncompra',
            name='secuencia',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
