# Generated by Django 5.1.3 on 2026-03-02 19:29

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0125_comprobante_retencion_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comprobanteretencion',
            new_name='inventario__empresa_22c777_idx',
            old_name='inventario_c_empresa_2662b2_idx',
        ),
        migrations.RenameIndex(
            model_name='comprobanteretencion',
            new_name='inventario__empresa_71656b_idx',
            old_name='inventario_c_empresa_9952ba_idx',
        ),
        migrations.RenameIndex(
            model_name='retenciondetalle',
            new_name='inventario__tipo_im_9f1482_idx',
            old_name='inventario_r_tipo_im_0f8ede_idx',
        ),
        migrations.AlterField(
            model_name='comprobanteretencion',
            name='base_exento_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='comprobanteretencion',
            name='base_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='comprobanteretencion',
            name='base_iva_0',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='comprobanteretencion',
            name='base_iva_5',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='comprobanteretencion',
            name='base_no_obj_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='comprobanteretencion',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='comprobanteretencion',
            name='fecha_emision_retencion',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='comprobanteretencion',
            name='monto_ice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='comprobanteretencion',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='comprobanteretencion',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='comprobanteretencion',
            name='total_retencion_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='comprobanteretencion',
            name='total_retencion_renta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='comprobanteretencion',
            name='total_retenido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='retenciondetalle',
            name='base_imponible',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='retenciondetalle',
            name='valor_retenido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
