# Generated by GitHub Copilot on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0126_rename_inventario_c_empresa_2662b2_idx_inventario__empresa_22c777_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteretencion',
            name='xml_generado',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='xml_validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comprobanteretencion',
            name='xml_validacion_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
