# Generated by Django 5.1.3 on 2026-03-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0132_liquidacioncompra_email_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacredito',
            name='estado_sri',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('RECIBIDA', 'Recibida'), ('RECIBIDO', 'Recibido'), ('AUTORIZADO', 'Autorizado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='estado_sri',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('RECIBIDA', 'Recibida'), ('RECIBIDO', 'Recibido'), ('AUTORIZADO', 'Autorizado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20),
        ),
    ]
