# Generated by Django 5.1.3 on 2026-03-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0133_alter_notacredito_estado_sri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteretencion',
            name='tipo_documento_sustento',
            field=models.CharField(choices=[('01', '(01) Factura'), ('03', '(03) Liquidación de Compra'), ('05', '(05) Nota de Débito')], default='01', max_length=2),
        ),
    ]
