"""
Django settings for sistema project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import warnings
from dotenv import load_dotenv
from cryptography.fernet import Fernet
import dj_database_url

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

load_dotenv()

# Seguridad y configuración sensible desde .env
DEBUG = os.environ.get('DEBUG', 'False') == 'True'
# Tiempo de espera por defecto para los servicios del SRI (en segundos)
SRI_TIMEOUT = int(os.environ.get('SRI_TIMEOUT', 30))

# Configuración de monitoreo con Sentry
SENTRY_DSN = os.environ.get('SENTRY_DSN')
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', 0.0)),
    )

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


STATIC_URL = '/static/'
# Incluye solo directorios de estáticos que existan para evitar advertencias
STATICFILES_DIRS = [
    p for p in [
        os.path.join(BASE_DIR, 'static'),
        os.path.join(BASE_DIR, 'inventario', 'static'),
    ] if os.path.isdir(p)
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
import os
# ✅ CONFIGURACIÓN DE MEDIOS (NUEVA O VERIFICAR)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Directorio separado y seguro para certificados de firma electrónica
FIRMAS_ROOT = os.path.join(BASE_DIR, 'firmas_secure')
# Clave utilizada para cifrar los archivos de firma; debe definirse en variables de entorno en producción
env_firmas_key = os.environ.get('FIRMAS_KEY')
if not env_firmas_key:
    # Permitir ausencia en desarrollo / pruebas, pero advertir claramente.
    FIRMAS_KEY = None
    warnings.warn(
        'FIRMAS_KEY no está configurada: las firmas electrónicas se almacenarán SIN CIFRAR. '
        'Configura FIRMAS_KEY en producción para habilitar cifrado (Fernet urlsafe base64 key).',
        RuntimeWarning
    )
else:
    FIRMAS_KEY = env_firmas_key.encode('utf-8')
    try:
        Fernet(FIRMAS_KEY)  # valida formato
    except ValueError as exc:
        raise ValueError('FIRMAS_KEY no es una clave Fernet válida') from exc

# ✅ CONFIGURACIÓN DE LOGGING (ROTACIÓN, JSON Y TENANT)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'fmt': '%(asctime)s %(levelname)s %(name)s %(tenant_id)s %(message)s',
        },
    },
    'filters': {
        'tenant_context': {
            '()': 'inventario.tenant.logging.TenantContextFilter',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': 'facturas.log',
            'when': 'midnight',
            'backupCount': 7,
            'formatter': 'json',
            'filters': ['tenant_context'],
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'json',
            'filters': ['tenant_context'],
        },
    },
    'loggers': {
        'sri': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        # ✅ NUEVO: Suprimir logs de debug de zeep y urllib3
        'zeep': {
            'handlers': ['console'],
            'level': 'WARNING',  # Solo errores y warnings, no debug
            'propagate': False,
        },
        'zeep.xsd.schema': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'zeep.transports': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'zeep.wsdl.wsdl': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'urllib3.connectionpool': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Mantener logs importantes del SRI
        'inventario.sri.sri_client': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
# Alternativamente, usar variables de entorno para mayor seguridad


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise Exception('SECRET_KEY no está configurada en el entorno')

# SECURITY WARNING: don't run with debug turned on in production!
# (DEBUG ya está arriba)

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []

# Configuración CORS
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if os.environ.get('CORS_ALLOWED_ORIGINS') else []

# Seguridad adicional
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []
SECURE_REFERRER_POLICY = os.environ.get('SECURE_REFERRER_POLICY', 'same-origin')
SECURE_CONTENT_TYPE_NOSNIFF = os.environ.get('SECURE_CONTENT_TYPE_NOSNIFF', 'True') == 'True'
SECURE_BROWSER_XSS_FILTER = os.environ.get('SECURE_BROWSER_XSS_FILTER', 'True') == 'True'
# Permite forzar HTTPS mediante una variable de entorno dedicada
# Establecer en True solo en entornos con HTTPS
FORCE_SSL = os.environ.get('FORCE_SSL', 'False').lower() == 'true'

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'inventario.apps.InventarioConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'inventario.tenant.middleware.TenantMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sistema.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema.wsgi.application'


# Database (solo PostgreSQL)
# Elimina completamente cualquier fallback a SQLite.
# Formas soportadas:
# 1. Usar DATABASE_URL (Heroku / contenedores): postgres://USER:PASSWORD@HOST:PORT/DBNAME
# 2. Usar variables individuales: PGHOST, PGPORT, PGDATABASE, PGUSER, PGPASSWORD (o DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASSWORD)

DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600, ssl_require=os.environ.get('DB_SSL_REQUIRE', 'false').lower() == 'true')
    }
else:
    # Construcción explícita vía variables. Acepta prefijos DB_ o PG.
    db_host = os.environ.get('DB_HOST') or os.environ.get('PGHOST')
    db_port = os.environ.get('DB_PORT') or os.environ.get('PGPORT') or '5432'
    db_name = os.environ.get('DB_NAME') or os.environ.get('PGDATABASE')
    db_user = os.environ.get('DB_USER') or os.environ.get('PGUSER')
    db_password = os.environ.get('DB_PASSWORD') or os.environ.get('PGPASSWORD')

    missing = [k for k,v in [
        ('DB_HOST/PGHOST', db_host),
        ('DB_NAME/PGDATABASE', db_name),
        ('DB_USER/PGUSER', db_user),
        ('DB_PASSWORD/PGPASSWORD', db_password),
    ] if not v]
    if missing:
        raise Exception(f"Configuración PostgreSQL incompleta. Faltan: {', '.join(missing)}. Define DATABASE_URL o variables DB_/PG_.")

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'HOST': db_host,
            'PORT': db_port,
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'CONN_MAX_AGE': 600,
        }
    }

# Mantiene las conexiones de base de datos abiertas durante 10 minutos
CONN_MAX_AGE = 600

# Ajustes de seguridad aplicados solo en producción
if not DEBUG:
    # Redirigir a HTTPS solo si se especifica explícitamente
    SECURE_SSL_REDIRECT = FORCE_SSL
    if FORCE_SSL:
        # Reconoce el encabezado enviado por el proxy para detectar HTTPS
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    SESSION_COOKIE_SECURE = FORCE_SSL
    CSRF_COOKIE_SECURE = FORCE_SSL
    SECURE_HSTS_SECONDS = 31536000


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'


AUTH_USER_MODEL = 'inventario.Usuario' # modelo de usuario

# Permite deshabilitar migraciones del app inventario en entornos de prueba
import os
if os.environ.get('DISABLE_INVENTARIO_MIGRATIONS'):
    MIGRATION_MODULES = {'inventario': None}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================
# Email configuration
# ==============================
# Default: console backend in development to avoid SMTP connection errors.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@example.com')
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

# SMTP settings (used if EMAIL_BACKEND is SMTP)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
try:
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 25))
except Exception:
    EMAIL_PORT = 25
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'False') == 'True'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Configuración global de Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '1000/day',
        'anon': '100/day',
    },
}
