"""
Django settings for sistema project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys
import warnings
from datetime import timedelta

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from cryptography.fernet import Fernet
import dj_database_url

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

load_dotenv()

ENVIRONMENT = (os.environ.get('ENVIRONMENT') or os.environ.get('DJANGO_ENV') or 'development').strip().lower() or 'development'
IS_TEST_ENV = bool(os.environ.get('PYTEST_CURRENT_TEST')) or any(arg in ('test', 'pytest') for arg in sys.argv)
IS_PRODUCTION = ENVIRONMENT in {'production', 'prod'} and not IS_TEST_ENV

# Seguridad y configuración sensible desde .env
DEBUG = os.environ.get('DEBUG', 'False') == 'True'
# Temporalmente deshabilitado para debugging en producción
# if IS_PRODUCTION and DEBUG:
#     warnings.warn('DEBUG está activo en producción; se forzará a False.', RuntimeWarning)
#     DEBUG = False
# Tiempo de espera por defecto para los servicios del SRI (en segundos)
SRI_TIMEOUT = int(os.environ.get('SRI_TIMEOUT', 30))

if IS_PRODUCTION and not os.environ.get('AWS_STORAGE_BUCKET_NAME'):
    raise RuntimeError(
        'AWS_STORAGE_BUCKET_NAME es obligatorio en producción para almacenar las firmas en S3.'
    )

# Configuración de monitoreo con Sentry
SENTRY_DSN = os.environ.get('SENTRY_DSN')
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', 0.0)),
    )

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


STATIC_URL = '/static/'
# Incluye solo directorios de estáticos que existan para evitar advertencias
STATICFILES_DIRS = [
    p for p in [
        os.path.join(BASE_DIR, 'static'),
        os.path.join(BASE_DIR, 'inventario', 'static'),
    ] if os.path.isdir(p)
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# ✅ CONFIGURACIÓN DE MEDIOS / ALMACENAMIENTO REMOTO
MEDIA_URL = os.environ.get('MEDIA_URL', '/media/')
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))
MEDIA_STORAGE_PREFIX = os.environ.get('MEDIA_STORAGE_PREFIX', '').strip('/')

# ✅ Usar S3 en producción (Heroku) y local en desarrollo
USE_REMOTE_MEDIA_STORAGE = bool(os.environ.get('AWS_STORAGE_BUCKET_NAME')) or IS_PRODUCTION

if USE_REMOTE_MEDIA_STORAGE:
    # Añadiremos 'storages' luego de declarar INSTALLED_APPS (más abajo) para evitar NameError
    _ADD_STORAGES = True

    AWS_STORAGE_BUCKET_NAME = os.environ['AWS_STORAGE_BUCKET_NAME']
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL')
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN')
    AWS_S3_SIGNATURE_VERSION = os.environ.get('AWS_S3_SIGNATURE_VERSION', 's3v4')
    AWS_S3_ADDRESSING_STYLE = os.environ.get('AWS_S3_ADDRESSING_STYLE')
    AWS_DEFAULT_ACL = os.environ.get('AWS_DEFAULT_ACL', 'private')
    # AWS_S3_QUERYSTRING_AUTH solo debe desactivarse (False) en pruebas locales controladas.
    AWS_QUERYSTRING_AUTH = os.environ.get('AWS_S3_QUERYSTRING_AUTH', '').lower() != 'false'
    AWS_S3_FILE_OVERWRITE = False

    AWS_S3_ENCRYPTION = True
    AWS_S3_KMS_KEY_ID = os.environ.get('AWS_S3_KMS_KEY_ID') or os.environ.get('AWS_KMS_KEY_ID')
    _default_sse = os.environ.get('AWS_S3_SERVER_SIDE_ENCRYPTION', 'aws:kms')

    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': os.environ.get('AWS_S3_CACHE_CONTROL', 'max-age=86400'),
        'ServerSideEncryption': _default_sse,
    }
    if _default_sse == 'aws:kms' and AWS_S3_KMS_KEY_ID:
        AWS_S3_OBJECT_PARAMETERS['SSEKMSKeyId'] = AWS_S3_KMS_KEY_ID

    AWS_S3_PRESIGNED_TTL = int(os.environ.get('AWS_S3_PRESIGNED_TTL', 3600))

    aws_location = os.environ.get('AWS_MEDIA_LOCATION') or os.environ.get('AWS_LOCATION', '')
    aws_location = (aws_location or '').strip('/')
    if aws_location and not MEDIA_STORAGE_PREFIX:
        MEDIA_STORAGE_PREFIX = aws_location

    # ✅ Django 5.1+ usa STORAGES en lugar de DEFAULT_FILE_STORAGE
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
        },
    }

    def _normalize_base_url(value: str) -> str:
        value = value.strip()
        if not value:
            return ''
        if not value.startswith(('http://', 'https://')):
            value = f'https://{value}'
        return value.rstrip('/')

    if os.environ.get('MEDIA_URL'):
        MEDIA_URL = os.environ['MEDIA_URL'].rstrip('/') + '/'
    else:
        if AWS_S3_CUSTOM_DOMAIN:
            base_url = _normalize_base_url(AWS_S3_CUSTOM_DOMAIN)
        elif AWS_S3_ENDPOINT_URL:
            base_url = _normalize_base_url(AWS_S3_ENDPOINT_URL)
        elif AWS_S3_REGION_NAME:
            base_url = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"
        else:
            base_url = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"

        prefix = MEDIA_STORAGE_PREFIX or aws_location
        if prefix:
            MEDIA_URL = f"{base_url}/{prefix}/"
        else:
            MEDIA_URL = f"{base_url}/"

    MEDIA_ROOT = ''
else:
    # ✅ Almacenamiento local (desarrollo o sin S3)
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
        },
    }
    print("⚠️ Usando almacenamiento local - Los archivos se pueden perder en Heroku")

# ✅ Configuración de WhiteNoise - No fallar por archivos faltantes en CSS
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_ALLOW_ALL_ORIGINS = True

# Directorio separado y seguro para certificados de firma electrónica
FIRMAS_ROOT = os.environ.get('FIRMAS_ROOT', os.path.join(BASE_DIR, 'firmas_secure'))

raw_firmas_prefix = os.environ.get('FIRMAS_STORAGE_PREFIX')
if raw_firmas_prefix:
    FIRMAS_STORAGE_PREFIX = raw_firmas_prefix.strip('/')
else:
    if IS_PRODUCTION:
        raise RuntimeError(
            'FIRMAS_STORAGE_PREFIX es obligatorio en producción para aislar los certificados en S3.'
        )
    FIRMAS_STORAGE_PREFIX = 'firmas_secure'

# Clave utilizada para cifrar los archivos de firma
env_firmas_key = os.environ.get('FIRMAS_KEY')
if not env_firmas_key:
    # Permitir ausencia de FIRMAS_KEY - las firmas se guardarán sin cifrar
    FIRMAS_KEY = None
    if IS_PRODUCTION:
        warnings.warn(
            'FIRMAS_KEY no configurada: las firmas electrónicas se almacenarán SIN CIFRAR. '
            'Para mayor seguridad, configura FIRMAS_KEY con una clave Fernet válida.',
            RuntimeWarning
        )
else:
    # Limpiar espacios, comillas y caracteres invisibles
    cleaned_key = env_firmas_key.strip().strip('"').strip("'").strip()
    FIRMAS_KEY = cleaned_key.encode('utf-8')
    try:
        Fernet(FIRMAS_KEY)  # valida formato
    except ValueError as exc:
        # Si la clave es inválida, advertir pero NO romper la app
        warnings.warn(
            f'FIRMAS_KEY inválida (longitud: {len(cleaned_key)}), se almacenarán firmas SIN CIFRAR. '
            f'Valor recibido: "{cleaned_key[:10]}..."',
            RuntimeWarning
        )
        FIRMAS_KEY = None

# ✅ Cache distribuida y Redis para tareas asíncronas
_raw_redis_sources = [
    os.environ.get('RQ_REDIS_URL'),
    os.environ.get('REDIS_URL'),
    os.environ.get('REDIS_TLS_URL'),
    os.environ.get('CACHE_URL'),
    os.environ.get('REDISCLOUD_URL'),
]
REDIS_URL = next((url for url in _raw_redis_sources if url), None)
CACHE_DEFAULT_TIMEOUT = int(os.environ.get('CACHE_DEFAULT_TIMEOUT', 300))

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': CACHE_DEFAULT_TIMEOUT,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                'SOCKET_CONNECT_TIMEOUT': int(os.environ.get('REDIS_SOCKET_CONNECT_TIMEOUT', 5)),
                'SOCKET_TIMEOUT': int(os.environ.get('REDIS_SOCKET_TIMEOUT', 5)),
            },
        }
    }
    DJANGO_REDIS_IGNORE_EXCEPTIONS = True
    SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
    SESSION_CACHE_ALIAS = 'default'
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'catalinafact-locmem',
            'TIMEOUT': CACHE_DEFAULT_TIMEOUT,
        }
    }

# ✅ CONFIGURACIÓN DE LOGGING (JSON, TENANT Y STDOUT)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'fmt': '%(asctime)s %(levelname)s %(name)s %(tenant_id)s %(message)s',
        },
    },
    'filters': {
        'tenant_context': {
            '()': 'inventario.tenant.logging.TenantContextFilter',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'formatter': 'json',
            'filters': ['tenant_context'],
        },
    },
    'loggers': {
        'sri': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        # ✅ NUEVO: Suprimir logs de debug de zeep y urllib3
        'zeep': {
            'handlers': ['console'],
            'level': 'WARNING',  # Solo errores y warnings, no debug
            'propagate': False,
        },
        'zeep.xsd.schema': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'zeep.transports': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'zeep.wsdl.wsdl': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'urllib3.connectionpool': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Mantener logs importantes del SRI
        'inventario.sri.sri_client': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
# Alternativamente, usar variables de entorno para mayor seguridad


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
try:
    SECRET_KEY = os.environ['SECRET_KEY']
except KeyError as exc:
    raise ImproperlyConfigured('SECRET_KEY no está configurada en el entorno') from exc

# SECURITY WARNING: don't run with debug turned on in production!
# (DEBUG ya está arriba)

# ✅ ALLOWED_HOSTS - Dominios permitidos
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []
# Agregar dominios personalizados
ALLOWED_HOSTS.extend([
    'catalinasoft-ec.com',
    'www.catalinasoft-ec.com',
    'localhost',
    '127.0.0.1',
])
# Remover duplicados y vacíos
ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS if h.strip()]

# Configuración CORS
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if os.environ.get('CORS_ALLOWED_ORIGINS') else []
# Agregar orígenes CORS para los dominios personalizados
CORS_ALLOWED_ORIGINS.extend([
    'https://catalinasoft-ec.com',
    'https://www.catalinasoft-ec.com',
])
CORS_ALLOWED_ORIGINS = [o.strip() for o in CORS_ALLOWED_ORIGINS if o.strip()]

# Seguridad adicional
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []
# Agregar orígenes confiables para CSRF
CSRF_TRUSTED_ORIGINS.extend([
    'https://catalinasoft-ec.com',
    'https://www.catalinasoft-ec.com',
])
CSRF_TRUSTED_ORIGINS = [o.strip() for o in CSRF_TRUSTED_ORIGINS if o.strip()]
SECURE_REFERRER_POLICY = os.environ.get('SECURE_REFERRER_POLICY', 'same-origin')
SECURE_CONTENT_TYPE_NOSNIFF = os.environ.get('SECURE_CONTENT_TYPE_NOSNIFF', 'True') == 'True'
SECURE_BROWSER_XSS_FILTER = os.environ.get('SECURE_BROWSER_XSS_FILTER', 'True') == 'True'
X_FRAME_OPTIONS = 'DENY'  # Protección contra clickjacking

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'django_rq',
    'axes',
    'inventario.apps.InventarioConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
if globals().get('_ADD_STORAGES'):
    INSTALLED_APPS.append('storages')

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'sistema.middleware.AdminIPAllowlistMiddleware',
    'inventario.tenant.middleware.TenantMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

_raw_admin_ip_allowlist = os.environ.get('ADMIN_IP_ALLOWLIST')
if IS_PRODUCTION and not (_raw_admin_ip_allowlist or '').strip():
    raise RuntimeError(
        'ADMIN_IP_ALLOWLIST es obligatorio en producción y debe incluir al menos una IP o red.'
    )
_raw_admin_ip_allowlist = (_raw_admin_ip_allowlist or '')
ADMIN_IP_ALLOWLIST = [
    ip.strip()
    for ip in _raw_admin_ip_allowlist.split(',')
    if ip.strip()
]
ADMIN_TRUSTED_HEADER = os.environ.get('ADMIN_TRUSTED_HEADER')
ADMIN_TRUSTED_HEADER_VALUES = [
    value.strip()
    for value in os.environ.get('ADMIN_TRUSTED_HEADER_VALUES', '').split(',')
    if value.strip()
]

_raw_root_admin_url = os.environ.get('ROOT_ADMIN_URL')
if IS_PRODUCTION and not (_raw_root_admin_url or '').strip():
    raise RuntimeError('ROOT_ADMIN_URL es obligatorio en producción y no puede estar vacío.')
_root_admin_path = (_raw_root_admin_url or 'admin').strip('/') or 'admin'
_tenant_admin_segment = (
    os.environ.get('TENANT_ADMIN_URL_SEGMENT', 'admin').strip('/') or 'admin'
)

ROOT_ADMIN_URL = _root_admin_path
TENANT_ADMIN_URL_SEGMENT = _tenant_admin_segment

ROOT_URLCONF = 'sistema.urls'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AXES_FAILURE_LIMIT = int(os.environ.get('AXES_FAILURE_LIMIT', 5))
AXES_RESET_ON_SUCCESS = True
AXES_ONLY_USER_FAILURES = True
AXES_LOCKOUT_PARAMETERS = ['username']
_raw_axes_cooloff = os.environ.get('AXES_COOLOFF_MINUTES')
if _raw_axes_cooloff:
    try:
        AXES_COOLOFF_TIME = timedelta(minutes=int(_raw_axes_cooloff))
    except ValueError:
        warnings.warn(
            'AXES_COOLOFF_MINUTES debe ser un entero; se usará el valor por defecto de 15 minutos.',
            RuntimeWarning,
        )
        AXES_COOLOFF_TIME = timedelta(minutes=15)
else:
    AXES_COOLOFF_TIME = timedelta(minutes=15)
AXES_META_PRECEDENCE_ORDER = ['HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR']

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema.wsgi.application'


# Database (solo PostgreSQL)
# Elimina completamente cualquier fallback a SQLite.
# Formas soportadas:
# 1. Usar DATABASE_URL (Heroku / contenedores): postgres://USER:PASSWORD@HOST:PORT/DBNAME
# 2. Usar variables individuales: PGHOST, PGPORT, PGDATABASE, PGUSER, PGPASSWORD (o DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASSWORD)

DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600, ssl_require=os.environ.get('DB_SSL_REQUIRE', 'false').lower() == 'true')
    }
else:
    # Construcción explícita vía variables. Acepta prefijos DB_ o PG.
    db_host = os.environ.get('DB_HOST') or os.environ.get('PGHOST')
    db_port = os.environ.get('DB_PORT') or os.environ.get('PGPORT') or '5432'
    db_name = os.environ.get('DB_NAME') or os.environ.get('PGDATABASE')
    db_user = os.environ.get('DB_USER') or os.environ.get('PGUSER')
    db_password = os.environ.get('DB_PASSWORD') or os.environ.get('PGPASSWORD')

    missing = [k for k,v in [
        ('DB_HOST/PGHOST', db_host),
        ('DB_NAME/PGDATABASE', db_name),
        ('DB_USER/PGUSER', db_user),
        ('DB_PASSWORD/PGPASSWORD', db_password),
    ] if not v]
    if missing:
        raise Exception(f"Configuración PostgreSQL incompleta. Faltan: {', '.join(missing)}. Define DATABASE_URL o variables DB_/PG_.")

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'HOST': db_host,
            'PORT': db_port,
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'CONN_MAX_AGE': 600,
        }
    }

# Mantiene las conexiones de base de datos abiertas durante 10 minutos
CONN_MAX_AGE = 600

# Ajustes de seguridad aplicados solo en producción
if not DEBUG:
    # Redirige todo el tráfico a HTTPS cuando el proyecto no está en modo debug
    SECURE_SSL_REDIRECT = True
    # Reconoce el encabezado enviado por el proxy para detectar HTTPS (Heroku, Nginx, etc.)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'  # Protección contra CSRF
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Lax'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # ✅ VALIDACIONES DE CONTRASEÑA DESHABILITADAS para permitir contraseñas simples y rápidas
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Usar hora oficial de Ecuador para generación de comprobantes y firmas
TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'


AUTH_USER_MODEL = 'inventario.Usuario' # modelo de usuario

# Permite deshabilitar migraciones del app inventario en entornos de prueba
import os
if os.environ.get('DISABLE_INVENTARIO_MIGRATIONS'):
    MIGRATION_MODULES = {'inventario': None}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de correo (Zeptomail por defecto)
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.zeptomail.com')
try:
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
except Exception:
    EMAIL_PORT = 587
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() == 'true'

# Email credentials - opcionales para evitar crashes
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'emailapikey')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Asegurar remitente por defecto acorde a Zeptomail
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@catalinasoft-ec.com')
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

# URL del sitio para correos electrónicos
SITE_URL = os.environ.get('SITE_URL', 'https://www.catalinasoft-ec.com')

# Configuración global de Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '1000/day',
        'anon': '100/day',
    },
}

# ✅ Configuración de colas asíncronas (django-rq)
RQ_DEFAULT_TIMEOUT = int(os.environ.get('RQ_DEFAULT_TIMEOUT', 420))
_rq_url = os.environ.get('RQ_REDIS_URL') or REDIS_URL or 'redis://127.0.0.1:6379/0'
RQ_QUEUES = {
    'default': {
        'URL': _rq_url,
        'DEFAULT_TIMEOUT': RQ_DEFAULT_TIMEOUT,
    },
    'sri': {
        'URL': _rq_url,
        'DEFAULT_TIMEOUT': int(os.environ.get('RQ_SRI_TIMEOUT', max(RQ_DEFAULT_TIMEOUT, 600))),
    },
    'reportes': {
        'URL': _rq_url,
        'DEFAULT_TIMEOUT': int(os.environ.get('RQ_REPORTES_TIMEOUT', max(RQ_DEFAULT_TIMEOUT, 900))),
    },
}

_rq_handlers = [handler.strip() for handler in os.environ.get(
    'RQ_EXCEPTION_HANDLERS',
    'django_rq.handlers.move_to_failed_queue',
).split(',') if handler.strip()]
if _rq_handlers:
    RQ_EXCEPTION_HANDLERS = _rq_handlers
